import type { CapacityPlanningRecord } from "@/services/types";

export const DEFAULT_CAPACITY_PLANNING_RECORD: CapacityPlanningRecord = {
  id: "proc-cap-rec-00027",
  planningId: "CP-2024-00027",
  formCode: "CPF-2024-25",
  projectName: "EV Charger Production Capacity Plan",
  planningVersion: "v1.2.0",
  workflowStatus: "In Progress",
  stage: 2,
  createdOn: "18 Jun 2024 09:30 AM",
  dateCreated: "2024-06-18T09:30:00Z",
  lastModified: "2024-06-20T14:15:00Z",
  lastUpdated: "20 Jun 2024 02:15 PM",
  plantName: "Magnertia Plant - 01",
  businessUnit: "EV Charger Division",
  engineerName: "Rahul Sharma",
  engineerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  planningPeriod: "Jul 2024 - Jun 2025",
  developmentStage: "Capacity Assessment",
  nextReviewDate: "25 Jun 2024",
  demandForecastUnits: 120000,
  plannedProductionUnits: 118000,
  capacityUtilization: 78,
  oeePercentage: 82,
  bottleneckCount: 2,
  availableMachineHours: 4200,
  availableLabourHours: 8500,
  productionLineCapacity: 125000,
  workstationCapacity: 122000,
  equipmentUtilization: 82,
  assessmentScore: 88,
  allocatedMachines: 68,
  totalMachines: 80,
  allocatedWorkforce: 320,
  totalWorkforce: 360,
  materialAvailability: 94,
  toolAvailability: 95,
  utilityAvailability: 100,
  shiftPattern: "3 Shifts / Day (24x7)",
  resourceScore: 86,
  bottlenecks: [
    { id: "btn-001", workstation: "WS-40", equipment: "Coil Winding Machine", constraint: "Machine Capacity", impact: "High", rootCause: "High cycle time during winding phase", improvementActions: "Add 1 parallel automated winder", estimatedGain: "+15% line throughput" },
    { id: "btn-002", workstation: "WS-70", equipment: "Testing Station", constraint: "Labour Capacity", impact: "High", rootCause: "Manual high-voltage test sequence", improvementActions: "Automate test rig software", estimatedGain: "+12% testing capacity" },
  ],
  bottleneckScore: 85,
  digitalTwinEnabled: true,
  activeScenario: "Peak Demand (Q3)",
  simulationScore: 86,
  lineEfficiency: 85,
  deliveryPerformance: 94,
  costPerUnit: 1420,
  performanceScore: 84,
  aiDemandForecastInsight: "Q3 demand will increase by 18% based on market trend vectors.",
  aiCapacityOptimization: "Increase Line 3 shifts for +12% capacity headroom.",
  aiBottleneckPrediction: "WS-40 may become critical in Aug 2024 under peak load.",
  aiExpansionRecommendation: "Add 1 Testing Station to reduce testing bottleneck.",
  aiWorkforceOptimization: "Reallocate 15 operators to Line 3 during shift 2.",
  aiCapacityScore: 88,
  overallCapacityReadiness: 87,
  recommendation: "Approve Capacity Plan",
  attachments: [
    { id: "catt-001", fileName: "capacity_calculation_sheet.xlsx", fileType: "xlsx", documentType: "Calculation Sheet", version: "v1.2", uploadedBy: "Rahul Sharma", uploadedDate: "18 Jun 2024", fileSize: "120 KB", status: "Active" },
  ],
  reviewers: [
    { role: "Capacity Planning Engineer", person: "Rahul Sharma", decision: "Approved", date: "18 Jun 2024", comments: "Plan prepared", status: "Approved" },
    { role: "Plant Head", person: "Neha Reddy", decision: "Pending", date: "-", comments: "Under review", status: "Pending" },
  ],
  approvalDecision: "Approved",
  reviewComments: "Capacity planning model verified for EV Charger Division.",
  approvalDate: "20 Jun 2024",
  createdBy: "Rahul Sharma",
  createdDate: "18 Jun 2024 09:30 AM",
  lastModifiedBy: "Rahul Sharma",
  lastModifiedDate: "20 Jun 2024 02:15 PM",
  workflowStageLabel: "Capacity Assessment",
  timeline: [
    { label: "Demand Assessment Completed", date: "05 Jun 2024", status: "Completed" },
    { label: "Resource Allocation Completed", date: "10 Jun 2024", status: "Completed" },
    { label: "Review & Approval", date: "In Progress", status: "In Progress" },
  ],
  auditTrail: [
    { id: "clog-001", timestamp: "18 Jun 2024 09:30 AM", user: "Rahul Sharma", action: "Created Capacity Plan", description: "Initial creation of EV Charger Production Capacity Plan (CP-2024-00027)." },
  ],
  simulations: [
    { id: "csim-001", scenarioName: "Peak Demand (Q3)", simulationScore: 86, expansionRequirement: "Recommended (+1 Testing Rig)", passed: true, runDate: "18 Jun 2024" },
  ],
};
