import type { FactoryLayoutRecord } from "@/services/types";

export const DEFAULT_FACTORY_LAYOUT_RECORD: FactoryLayoutRecord = {
  id: "proc-fact-rec-0012",
  layoutId: "FLD-2024-0012",
  formCode: "FLF-2024-25",
  projectName: "EV Charger Manufacturing Plant Layout",
  layoutVersion: "v1.2.0",
  workflowStatus: "In Progress",
  stage: 3,
  createdOn: "18 Jun 2024 09:40 AM",
  dateCreated: "2024-06-18T09:40:00Z",
  lastModified: "2024-06-20T15:15:00Z",
  lastUpdated: "20 Jun 2024 03:15 PM",
  plantName: "Magnertia Plant - 01",
  facilityLocation: "Pune, Maharashtra, India",
  engineerName: "Rahul Sharma",
  engineerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  totalLandArea: 120000,
  builtUpArea: 45000,
  productionCapacity: 250000,
  nextReviewDate: "25 Jun 2024",
  factoryName: "Magnertia EV Plant",
  plantType: "Greenfield Factory",
  industrySegment: "Electric Vehicles",
  factoryObjective: "Design a world-class EV charger manufacturing facility with lean flow, high automation, and future expansion capability.",
  developmentStage: "Detailed Layout",
  priority: "High",
  masterLayoutDrawing: "master_layout_v1.2.dwg",
  shopFloorLayout: "shopfloor_layout_v1.2.dwg",
  productionLineLayout: "line_layout_v1.2.dwg",
  utilityLayout: "utility_layout_v1.2.dwg",
  materialFlowDiagram: "material_flow_v1.2.pdf",
  equipmentLayout: "equipment_layout_v1.2.dwg",
  warehouseLayout: "warehouse_layout_v1.2.dwg",
  officeLayout: "office_layout_v1.2.dwg",
  layoutPlanningScore: 88,
  productionAreas: ["Machining", "Assembly", "Testing", "Packing"],
  assemblyAreas: ["SMT", "Panel Assembly", "Final Assembly"],
  warehouseCapacityM2: 8500,
  loadingUnloadingBays: 6,
  utilitySystems: ["Electrical", "Compressed Air", "HVAC"],
  maintenanceWorkshop: true,
  infrastructureScore: 86,
  rawMaterialFlow: "raw_material_flow_v1.2.pdf",
  wipFlow: "wip_flow_v1.2.pdf",
  finishedGoodsFlow: "fg_flow_v1.2.pdf",
  forkliftRoutes: "forklift_routes_v1.2.pdf",
  agvAmrRoutes: "agv_routes_v1.2.pdf",
  materialHandlingEq: ["Forklift", "AGV", "Conveyor", "Overhead Crane"],
  logisticsScore: 85,
  electricalLayout: "electrical_layout_v1.2.dwg",
  compressedAirLayout: "cir_layout_v1.2.dwg",
  waterLayout: "water_layout_v1.2.dwg",
  fireSafetyLayout: "fire_safety_layout_v1.2.pdf",
  emergencyExitPlan: "emergency_exit_v1.2.pdf",
  ehsCompliance: true,
  utilitySafetyScore: 88,
  spaceUtilization: 78,
  materialTravelDistance: 1.62,
  throughputUnitsPerYear: 250000,
  warehouseEfficiency: 92,
  energyEfficiency: 86,
  equipmentAccessibility: 90,
  factoryEfficiencyScore: 87,
  aiLayoutOptimization: "AI suggests relocating SMT line to reduce material travel by 12%.",
  aiBottleneckPrediction: "Panel assembly zone may become a bottleneck at 85% capacity.",
  aiMaterialFlowOptimization: "AI optimizes AGV routes and storage locations for better flow.",
  aiCapacityExpansionRec: "Add 2 additional assembly cells in Phase 2 expansion.",
  aiSafetyImprovementRec: "AI suggests additional fire exits in warehouse zone.",
  aiFactoryScore: 89,
  overallFactoryReadiness: 87,
  recommendation: "Approve Factory Layout",
  attachments: [
    { id: "fatt-001", fileName: "factory_master_plan_v1.2.pdf", fileType: "pdf", documentType: "Master Layout", version: "v1.2", uploadedBy: "Rahul Sharma", uploadedDate: "18 Jun 2024", fileSize: "3.2 MB", status: "Active" },
    { id: "fatt-002", fileName: "digital_twin_model_v1.2.zip", fileType: "zip", documentType: "Digital Twin Model", version: "v1.2", uploadedBy: "Rahul Sharma", uploadedDate: "18 Jun 2024", fileSize: "65.6 MB", status: "Active" },
  ],
  reviewers: [
    { role: "Factory Layout Engineer", person: "Rahul Sharma", decision: "Approved", date: "18 Jun 2024", comments: "Layout completed", status: "Approved" },
    { role: "Manufacturing Engineer", person: "Naresh Verma", decision: "Approved", date: "18 Jun 2024", comments: "Flow is optimized", status: "Approved" },
    { role: "Facility Manager", person: "Neha Reddy", decision: "Pending", date: "-", comments: "Utility plan under review", status: "Pending" },
    { role: "Plant Head", person: "Sankaran R.", decision: "Pending", date: "-", comments: "Executive review", status: "Pending" },
  ],
  approvalDecision: "Approved",
  reviewComments: "Detailed factory layout design approved. Ready for construction sign-off.",
  approvalDate: "20 Jun 2024",
  createdBy: "Rahul Sharma",
  createdDate: "18 Jun 2024 09:40 AM",
  lastModifiedBy: "Rahul Sharma",
  lastModifiedDate: "20 Jun 2024 03:15 PM",
  workflowStageLabel: "Detailed Layout",
  timeline: [
    { label: "Site Planning Completed", date: "05 Jun 2024", status: "Completed" },
    { label: "Master Layout Completed", date: "07 Jun 2024", status: "Completed" },
    { label: "Simulation Completed", date: "18 Jun 2024", status: "Completed" },
    { label: "Review & Approval", date: "In Progress", status: "In Progress" },
    { label: "Implementation", date: "Pending", status: "Pending" },
  ],
  auditTrail: [
    { id: "flog-001", timestamp: "18 Jun 2024 09:40 AM", user: "Rahul Sharma", action: "Created Factory Layout Project", description: "Initial creation of EV Charger Manufacturing Plant Layout (FLD-2024-0012)." },
    { id: "flog-002", timestamp: "20 Jun 2024 03:15 PM", user: "Rahul Sharma", action: "Submitted for Review", description: "Factory Layout submitted for review board approval.", prevStatus: "In Progress", newStatus: "Under Review" },
  ],
  simulations: [
    { id: "sim-001", simulationType: "Material Flow Simulation", status: "Completed", resultSummary: "Material travel distance reduced by 23%. No AGV congestion detected.", passed: true, runDate: "18 Jun 2024" },
    { id: "sim-002", simulationType: "Throughput Capacity Simulation", status: "Completed", resultSummary: "Target 250,000 units/year throughput achievable at 82% line loading.", passed: true, runDate: "18 Jun 2024" },
  ],
};
