import type {
  CompanyRecord,
  BranchRecord,
} from "@/services/types";

export const companies: CompanyRecord[] = [
  {
    id: "CO-001",
    code: "MEVIP",
    name: "Magnertia EV Infrastructure Pvt Ltd",
    taxId: "29AABCM1234F1ZK",
    status: "Active",
    branchCount: 5,
    createdDate: "Jan 15, 2022",
  },
  {
    id: "CO-002",
    code: "MEVDL",
    name: "Magnertia EV Dealerships Ltd",
    taxId: "07AABCM5678G1ZQ",
    status: "Active",
    branchCount: 3,
    createdDate: "Mar 10, 2023",
  },
  {
    id: "CO-003",
    code: "MEVCH",
    name: "Magnertia Charge Network Pvt Ltd",
    taxId: "33AABCM9012H1ZR",
    status: "Active",
    branchCount: 2,
    createdDate: "Jun 22, 2023",
  },
  {
    id: "CO-004",
    code: "MEVBT",
    name: "Magnertia Battery Technologies Ltd",
    taxId: "27AABCM3456J1ZS",
    status: "Active",
    branchCount: 2,
    createdDate: "Sep 05, 2023",
  },
];

export const branches: BranchRecord[] = [
  {
    id: "BR-01",
    code: "BLR-HQ",
    name: "Bengaluru HQ",
    companyId: "CO-001",
    companyName: "Magnertia EV Infrastructure Pvt Ltd",
    city: "Bengaluru",
    status: "Active",
    departmentCount: 12,
  },
  {
    id: "BR-02",
    code: "PNE-FAC",
    name: "Pune Factory",
    companyId: "CO-001",
    companyName: "Magnertia EV Infrastructure Pvt Ltd",
    city: "Pune",
    status: "Active",
    departmentCount: 8,
  },
  {
    id: "BR-03",
    code: "CHN-RD",
    name: "Chennai R&D Center",
    companyId: "CO-001",
    companyName: "Magnertia EV Infrastructure Pvt Ltd",
    city: "Chennai",
    status: "Active",
    departmentCount: 6,
  },
  {
    id: "BR-04",
    code: "DLH-SO",
    name: "Delhi Sales Office",
    companyId: "CO-002",
    companyName: "Magnertia EV Dealerships Ltd",
    city: "New Delhi",
    status: "Active",
    departmentCount: 4,
  },
  {
    id: "BR-05",
    code: "MUM-SO",
    name: "Mumbai Sales Office",
    companyId: "CO-002",
    companyName: "Magnertia EV Dealerships Ltd",
    city: "Mumbai",
    status: "Active",
    departmentCount: 3,
  },
  {
    id: "BR-06",
    code: "HYD-CN",
    name: "Hyderabad Charge Hub",
    companyId: "CO-003",
    companyName: "Magnertia Charge Network Pvt Ltd",
    city: "Hyderabad",
    status: "Active",
    departmentCount: 2,
  },
  {
    id: "BR-07",
    code: "GJ-FAC",
    name: "Gujarat Battery Plant",
    companyId: "CO-004",
    companyName: "Magnertia Battery Technologies Ltd",
    city: "Ahmedabad",
    status: "Active",
    departmentCount: 5,
  },
];
