import type { WorkInstructionRecord, WorkInstructionStepItem } from "@/services/types";

export const DEFAULT_WORK_INSTRUCTION_STEPS: WorkInstructionStepItem[] = [
  { id: "step-1", stepNumber: 1, instruction: "Verify all components as per BOM.", visualReferenceUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300&auto=format&fit=crop&q=80", keyPoints: "Check quantity and part number.", timeSeconds: 20, safetyNotes: "Wear ESD anti-static wristband", qualityChecks: "Match BOM revision v2.0", requiredTools: "Barcode Scanner", requiredMaterials: "ACCU Components Kit" },
  { id: "step-2", stepNumber: 2, instruction: "Install PCB in bottom enclosure using M3 screws.", visualReferenceUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&auto=format&fit=crop&q=80", keyPoints: "Tighten screws with 0.8 Nm torque.", timeSeconds: 45, safetyNotes: "Avoid sharp enclosure edges", qualityChecks: "Check screw torque calibration", requiredTools: "Torque Screwdriver (0.5-2 Nm)", requiredMaterials: "PCB Assembly, M3 Screws" },
  { id: "step-3", stepNumber: 3, instruction: "Connect input power wires to terminal block.", visualReferenceUrl: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=300&auto=format&fit=crop&q=80", keyPoints: "Check wire color code.", timeSeconds: 30, safetyNotes: "Verify zero voltage de-energized state", qualityChecks: "Pull test wire connections (50N)", requiredTools: "Wire Cutter, Multimeter", requiredMaterials: "Power Cable Set" },
  { id: "step-4", stepNumber: 4, instruction: "Connect signal cables to PCB connectors.", visualReferenceUrl: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=300&auto=format&fit=crop&q=80", keyPoints: "Ensure locking mechanism is secure.", timeSeconds: 40, safetyNotes: "Prevent pin bending", qualityChecks: "Visual connector latch engage check", requiredTools: "Tweezers", requiredMaterials: "Signal Harness Assembly" },
  { id: "step-5", stepNumber: 5, instruction: "Install top cover and tighten all screws.", visualReferenceUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=300&auto=format&fit=crop&q=80", keyPoints: "Uniform torque 0.8 Nm.", timeSeconds: 35, safetyNotes: "Ensure gasket alignment for IP54 rating", qualityChecks: "No wire pinching under cover", requiredTools: "Torque Screwdriver", requiredMaterials: "Top Enclosure Cover, Gasket" },
  { id: "step-6", stepNumber: 6, instruction: "Perform functional test and verify LEDs.", visualReferenceUrl: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=300&auto=format&fit=crop&q=80", keyPoints: "All LEDs should be ON.", timeSeconds: 60, safetyNotes: "Use high voltage insulated gloves during test", qualityChecks: "First-Off Inspection passed", requiredTools: "ATE Test Rig, Multimeter", requiredMaterials: "Test Certification Sticker" },
];

export const DEFAULT_WORK_INSTRUCTION_RECORD: WorkInstructionRecord = {
  id: "proc-wi-rec-000256",
  instructionId: "WI-2024-000256",
  formCode: "WID-2024-25",
  title: "Assembly of AC Charging Control Unit",
  documentNumber: "WI-MAG-ACCU-001",
  revision: "2.0",
  workflowStatus: "In Review",
  stage: 2,
  createdOn: "18 Jun 2024 09:15 AM",
  dateCreated: "2024-06-18T09:15:00Z",
  effectiveDate: "20 Jun 2024",
  nextReviewDate: "20 Jun 2025",
  lastModified: "2024-06-20T14:45:00Z",
  lastUpdated: "20 Jun 2024 02:45 PM",
  plantName: "Magnertia Plant - 01",
  department: "Manufacturing",
  processOwner: "Rahul Sharma",
  processOwnerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  workstation: "WS-ACCU-01",
  productionLine: "Line-ACCU-01",
  productFamily: "AC Charger",
  productModel: "ACCU-7KW V1.0",
  processName: "Control Unit Assembly",
  operationNumber: "OP-20",
  operationDescription: "Assemble and test the AC Charging Control Unit including PCB installation, wiring, and enclosure assembly as per engineering specification.",
  instructionCategory: "Assembly",
  priority: "High",
  totalCycleTimeSec: 230,
  overallReadinessScore: 87,
  qualityScore: 85,
  safetyScore: 90,
  competencyScore: 84,
  aiDocumentationScore: 88,
  recommendation: "Approve Work Instruction",
  steps: DEFAULT_WORK_INSTRUCTION_STEPS,
  requiredTools: ["Torque Screwdriver (0.5-2 Nm)", "Phillips Screwdriver", "Wire Cutter", "Multimeter"],
  fixturesJigs: ["PCB Assembly Jig", "Insulated Unit Enclosure"],
  measuringInstruments: ["Digital Caliper", "Multimeter", "Torque Meter"],
  materials: ["PCB Assembly", "M3 Screws", "Power Cable Set", "First-Off Inspection Sticker"],
  ppeRequirements: ["ESD Anti-static Wristband", "Safety Glasses", "Insulated Gloves"],
  inspectionPoints: ["Visual PCB placement & orientation", "Screw torque 0.8 Nm verification", "Wire pull test 50N", "LED indicator status test"],
  acceptanceCriteria: "Zero wire pinching, all 4 LEDs green, screw torque within +/-0.05 Nm tolerance.",
  qualityChecklist: ["BOM Part Number verification ✓", "Torque calibration check ✓", "First-off inspection signoff ✓", "Hi-pot electrical safety test ✓"],
  hazardsIdentified: 3,
  lockoutTagoutRequired: false,
  ergonomicAssessment: "Ergonomic seating & anti-fatigue matting defined",
  regulatoryCompliance: true,
  trainingRequired: true,
  skillLevel: "Intermediate",
  authorizedOperators: 12,
  certificationRequired: true,
  aiInstructionReview: "All assembly steps are clear, complete, and properly sequenced.",
  aiRiskAssessment: "Low risk operation. Ensure ESD safety precautions during PCB placement.",
  aiProcessOptimization: "Use pre-assembled cable harness to reduce cycle time by 8%.",
  aiKnowledgeGapAnalysis: "Add reference image for screw torque setting knob.",
  aiTrainingRecommendation: "Refresher training recommended for 3 newly assigned operators.",
  attachments: [
    { id: "wiatt-001", fileName: "SOP_Control_Unit_Assembly.pdf", fileType: "pdf", documentType: "SOP Document", version: "v2.0", uploadedBy: "Rahul Sharma", uploadedDate: "18 Jun 2024", fileSize: "1.2 MB", status: "Active" },
  ],
  reviewers: [
    { role: "Process Engineer", person: "Rahul Sharma", decision: "Approved", date: "18 Jun 2024", comments: "Instructions created", status: "Approved" },
    { role: "Plant Head", person: "Sankaran R.", decision: "Pending", date: "-", comments: "Under review", status: "Pending" },
  ],
  approvalDecision: "Approved",
  reviewComments: "Work Instruction WI-2024-000256 approved for shop floor assembly release.",
  approvalDate: "20 Jun 2024",
  createdBy: "Rahul Sharma",
  createdDate: "18 Jun 2024 09:15 AM",
  lastModifiedBy: "Neha Reddy",
  lastModifiedDate: "20 Jun 2024 02:45 PM",
  workflowStageLabel: "Under Review",
  timeline: [
    { label: "Instruction Authoring", date: "18 Jun 2024", status: "Completed" },
    { label: "Quality & Safety Review", date: "19 Jun 2024", status: "Completed" },
    { label: "Executive Approval", date: "Pending", status: "Pending" },
  ],
  auditTrail: [
    { id: "wilog-001", timestamp: "18 Jun 2024 09:15 AM", user: "Rahul Sharma", action: "Created Work Instruction", description: "Initial authoring of Assembly of AC Charging Control Unit (WI-2024-000256)." },
  ],
};
