import { AuditRecord } from "./auditTypes";

export const INITIAL_AUDIT_RECORD: AuditRecord = {
  auditId: "aud-rec-2026-0018",
  auditNumber: "AUD-2026-0018",
  auditTitle: "Q3 Comprehensive Internal Quality & Process Audit",
  auditDate: "07-Sep-2026",
  scheduledEndDate: "10-Sep-2026",
  auditType: "Internal",
  auditCategory: "Quality Management System (ISO 9001)",
  standardReference: "ISO 9001:2015 / IATF 16949:2016",
  leadAuditor: "Dr. Anita Desai",
  auditTeam: ["Marcus Chen", "Priya S", "Rajesh Kumar"],
  auditScope: "Plant 1 SMT Lines, Through-Hole Soldering, Assembly Cells, & Final Quality Gates",
  auditLocation: "Main Manufacturing Campus - Facility 1",
  departmentAudited: "Production, Quality Assurance, Maintenance",
  auditStatus: "In Progress",
  workflowStatus: "Active Execution",
  conformanceRate: 88.5,

  totalItems: 42,
  compliantCount: 36,
  minorNcCount: 4,
  majorNcCount: 2,
  ofiCount: 3,

  objective:
    "Systematically verify operational compliance with ISO 9001:2015 Clause 7 (Support), Clause 8 (Operation), and Clause 9 (Performance Evaluation). Validate that in-process quality controls, calibration integrity, and standard work instructions are rigorously enforced on the manufacturing shop floor.",
  scopeSummary:
    "Encompasses discrete surface-mount production line SMT-01 to SMT-04, manual soldering workstations, automated optical inspection (AOI), ESD grounding stations, and quarantine segregation areas.",
  methodology:
    "Random sampling of 50 active job travelers, live process observation across two operational shifts, verification of calibration certificates, and structured operator interviews.",

  checklist: [
    {
      id: "chk-1",
      clauseRef: "Clause 7.1.5",
      requirement: "Monitoring and measuring resources are calibrated, verified, and traceable to national/international standards",
      areaDepartment: "Inspection Lab / QA",
      result: "Conforming",
      findingNote: "All 18 digital multimeters and micrometers verified with valid NABL certificates.",
      auditor: "Priya S",
    },
    {
      id: "chk-2",
      clauseRef: "Clause 7.5.3",
      requirement: "Control of documented information - current revisions accessible at points of use",
      areaDepartment: "SMT Line 2",
      result: "Conforming",
      findingNote: "Work Instructions rev 4.2 displayed on digital terminals; obsolete prints absent.",
      auditor: "Marcus Chen",
    },
    {
      id: "chk-3",
      clauseRef: "Clause 8.5.1",
      requirement: "Implementation of monitoring and measurement activities at designated in-process stages",
      areaDepartment: "Through-Hole Soldering",
      result: "Minor NC",
      findingNote: "Two hourly solder pot temperature logs missed during second shift changeover on Line 1.",
      auditor: "Rajesh Kumar",
      linkedNcr: "NCR-2026-0091",
    },
    {
      id: "chk-4",
      clauseRef: "Clause 8.5.2",
      requirement: "Identification and traceability - suitable means to identify outputs throughout production",
      areaDepartment: "SMT Line 1",
      result: "Major NC",
      findingNote: "15 PCB panels lacked barcoded batch serial tracking stickers in intermediate holding rack.",
      auditor: "Dr. Anita Desai",
      linkedNcr: "NCR-2026-0089",
    },
    {
      id: "chk-5",
      clauseRef: "Clause 8.5.4",
      requirement: "Preservation of outputs - handling, contamination control, packaging, and ESD protection",
      areaDepartment: "Assembly Line B",
      result: "Minor NC",
      findingNote: "One operator wrist strap failed daily resistivity test but remained logged as pass.",
      auditor: "Marcus Chen",
      linkedNcr: "NCR-2026-0092",
    },
    {
      id: "chk-6",
      clauseRef: "Clause 8.7",
      requirement: "Control of non-conforming outputs - segregation, identification, and quarantine controls",
      areaDepartment: "Inspection Area",
      result: "Conforming",
      findingNote: "Quarantine cage physically locked; ERP quarantine inventory status mirrored in real-time.",
      auditor: "Dr. Anita Desai",
    },
  ],

  findings: [
    {
      id: "fnd-1",
      findingNumber: "AUD-FND-001",
      clauseRef: "Clause 8.5.2",
      classification: "Major NC",
      description: "Batch traceability gap: 15 PCB panels without unique serialized barcoded travelers.",
      department: "Production (SMT)",
      responsiblePerson: "Suresh Menon",
      dueDate: "15-Sep-2026",
      status: "NCR Raised",
      ncrReference: "NCR-2026-0089",
    },
    {
      id: "fnd-2",
      findingNumber: "AUD-FND-002",
      clauseRef: "Clause 8.5.1",
      classification: "Minor NC",
      description: "Intermittent gap in hourly solder temperature check logging on Line 1.",
      department: "Manufacturing Operations",
      responsiblePerson: "Kavita Rao",
      dueDate: "20-Sep-2026",
      status: "NCR Raised",
      ncrReference: "NCR-2026-0091",
    },
    {
      id: "fnd-3",
      findingNumber: "AUD-FND-003",
      clauseRef: "Clause 8.5.4",
      classification: "Minor NC",
      description: "Operator ESD wrist strap resistivity check calibration protocol irregularity.",
      department: "Quality Assurance",
      responsiblePerson: "Priya S",
      dueDate: "18-Sep-2026",
      status: "NCR Raised",
      ncrReference: "NCR-2026-0092",
    },
    {
      id: "fnd-4",
      findingNumber: "AUD-FND-004",
      clauseRef: "Clause 7.1.3",
      classification: "Opportunity for Improvement (OFI)",
      description: "Recommend automated automated temperature/humidity sensors to replace manual hourly clipboard logging.",
      department: "Facilities & Maintenance",
      responsiblePerson: "Arun Verma",
      dueDate: "30-Sep-2026",
      status: "Open",
    },
  ],

  aiInsights: [
    {
      id: "ai-aud-1",
      text: "88.5% overall compliance rate is 3.5% above historical Q3 audit baseline (85%).",
      type: "success",
    },
    {
      id: "ai-aud-2",
      text: "Major NC on serialization (AUD-FND-001) linked to NCR-2026-0089 with immediate quarantine.",
      type: "alert",
    },
    {
      id: "ai-aud-3",
      text: "Calibration management clause (7.1.5) scored 100% full conformance across all sampled lines.",
      type: "info",
    },
    {
      id: "ai-aud-4",
      text: "Recommend scheduling follow-up verification audit on SMT line traceability by 25-Sep-2026.",
      type: "warning",
    },
  ],
};
