import { CalibrationRecord } from "./calibrationTypes";

export const INITIAL_CALIBRATION_RECORD: CalibrationRecord = {
  calibrationId: "cal-rec-2026-0047",
  calibrationNumber: "CAL-2026-0047",
  calibrationDate: "06-Sep-2026",
  calibrationType: "External",
  calibrationStatus: "In Progress",
  equipmentName: "Multimeter (Fluke 87V)",
  equipmentId: "EQP-EL-0018",
  equipmentType: "Electrical",
  department: "Quality Control",
  location: "Inspection Lab - Line 1",
  calibrationAgency: "TUV India Pvt. Ltd.",
  calibrationProcedure: "CAL-PROC-EL-001",
  calibrationFrequency: "Annual",
  previousCalibrationDate: "05-Sep-2025",
  nextCalibrationDate: "05-Sep-2027",
  priority: "High",
  calibrationOwner: "Priya S",

  equipmentInfo: {
    name: "Multimeter (Fluke 87V)",
    status: "Active",
    manufacturer: "Fluke",
    model: "87V",
    serialNumber: "45281567",
    assetNumber: "AST-EL-0092",
    range: "0.1 mV - 1000 V",
    accuracy: "±(0.1% + 1)",
    location: "Inspection Lab - Line 1",
  },

  preVerification: [
    { id: "pv-1", check: "Equipment Identification", result: "Pass" },
    { id: "pv-2", check: "Physical Condition", result: "Pass" },
    { id: "pv-3", check: "Display / Indicator", result: "Pass" },
    { id: "pv-4", check: "Power Supply", result: "Pass" },
    { id: "pv-5", check: "Accessories", result: "Pass" },
    { id: "pv-6", check: "Functional Check", result: "Pass" },
  ],

  standards: {
    referenceStandard: "Fluke 5500A Calibrator",
    standardSerialNo: "5500A-2234",
    certificateNo: "CERT-2026-1187",
    validUntil: "10-Jan-2027",
    traceabilityStatement:
      "Traceability: Equipment → Reference Standard → Accredited Laboratory → National Standard (NABL)",
  },

  environment: {
    temperature: 23.5,
    humidity: 52,
    pressure: 1012,
  },

  measurements: [
    {
      id: "m-1",
      seq: 1,
      parameter: "DC Voltage (V)",
      nominalValue: 10.0,
      standardReading: 10.002,
      equipmentReading: 10.001,
      error: -0.001,
      tolerance: "±0.02",
      result: "Pass",
      remarks: "Within tolerance",
    },
    {
      id: "m-2",
      seq: 2,
      parameter: "DC Voltage (V)",
      nominalValue: 100.0,
      standardReading: 100.005,
      equipmentReading: 100.008,
      error: 0.003,
      tolerance: "±0.05",
      result: "Pass",
      remarks: "Within tolerance",
    },
    {
      id: "m-3",
      seq: 3,
      parameter: "AC Voltage (V)",
      nominalValue: 230.0,
      standardReading: 229.98,
      equipmentReading: 229.4,
      error: -0.58,
      tolerance: "±1.00",
      result: "Pass",
      remarks: "Within tolerance",
    },
    {
      id: "m-4",
      seq: 4,
      parameter: "Resistance (Ω)",
      nominalValue: 1000.0,
      standardReading: 1000.3,
      equipmentReading: 1000.8,
      error: 0.5,
      tolerance: "±1.00",
      result: "Pass",
      remarks: "Within tolerance",
    },
    {
      id: "m-5",
      seq: 5,
      parameter: "Current (A)",
      nominalValue: 10.0,
      standardReading: 9.998,
      equipmentReading: 9.995,
      error: -0.003,
      tolerance: "±0.02",
      result: "Pass",
      remarks: "Within tolerance",
    },
  ],

  overallResult: "PASS",
  overallResultDescription: "Equipment is within specified tolerance and fit for use.",
  adjustmentPerformed: "No",
  complianceToProcedure: "Yes",
  measurementUncertainty: "±0.12 %",
  certificateNumber: "CAL-2026-0047",
  certificateIssueDate: "06-Sep-2026",
  certificateValidUntil: "05-Sep-2027",

  schedule: {
    scheduledDate: "01-Sep-2026",
    inProgressDate: "06-Sep-2026",
    nextDueDate: "05-Sep-2027",
  },

  aiInsights: [
    {
      id: "ai-1",
      text: "No significant drift detected in last 3 cycles.",
      type: "info",
    },
    {
      id: "ai-2",
      text: "Calibration due date optimized (annual).",
      type: "alert",
    },
    {
      id: "ai-3",
      text: "Historical accuracy is stable (99.2%).",
      type: "success",
    },
    {
      id: "ai-4",
      text: "Similar instruments show low failure risk.",
      type: "info",
    },
    {
      id: "ai-5",
      text: "Recommend to monitor input terminal wear.",
      type: "recommendation",
    },
  ],

  recentCalibrations: [
    {
      date: "06-Sep-2026",
      certificateNo: "CAL-2026-0047",
      result: "Pass",
      nextDue: "05-Sep-2027",
    },
    {
      date: "06-Sep-2025",
      certificateNo: "CAL-2025-0039",
      result: "Pass",
      nextDue: "05-Sep-2026",
    },
    {
      date: "12-Sep-2024",
      certificateNo: "CAL-2024-0021",
      result: "Pass",
      nextDue: "05-Sep-2025",
    },
  ],
};
