import { FqcRecord } from "./fqcTypes";

export const INITIAL_FQC_RECORD: FqcRecord = {
  id: "fqc-rec-00236",
  inspectionNo: "FQC-2026-00236",
  inspectionDate: "08-Sep-2026 10:45",
  productionOrder: "MO-2026-00087",
  workOrder: "WO-2026-00421",
  product: "Autonomous W-EVSE 7kW",
  productCode: "EVSE-7KW-001",
  productRevision: "REV-2.1",
  batchLotNo: "B-2026-09-014",
  serialRange: "SN001 - SN050",
  totalProducedQuantity: 50,
  inspectionQuantity: 50,
  acceptedQuantity: 48,
  rejectedQuantity: 2,
  samplingPlan: "100% End-of-Line Inspection",
  inspectionStage: "Final Assembly & Enclosure",
  inspector: "Rajesh K",
  qualityEngineer: "Arun K",
  inspectionStatus: "Completed",
  overallResult: "Conditional Pass",
  customerOrder: "SO-2026-0312",
  customer: "GreenMobility Pvt. Ltd.",

  dailyStats: {
    inspectionsToday: 286,
    passed: 264,
    failed: 12,
    onHold: 10,
    certificatesIssued: 254,
    firstPassYield: 92.3,
  },

  characteristics: [
    {
      id: "char-1",
      seq: 1,
      characteristic: "Enclosure Cosmetic Surface Finish",
      category: "Visual",
      specification: "No scratches, dents or cosmetic defects >0.1mm",
      nominal: "Pass",
      minTol: "-",
      maxTol: "-",
      unit: "Visual",
      inspectionMethod: "Visual 100% under 850 Lux",
      sampleSize: 50,
      actualMeasured: "2 units scratched (Segregated)",
      status: "Fail",
      remark: "Linked to NCR-2026-0047",
    },
    {
      id: "char-2",
      seq: 2,
      characteristic: "Overall Enclosure Dimensions (H x W x D)",
      category: "Dimensional",
      specification: "380 x 240 x 145 mm (±1.5mm)",
      nominal: 380,
      minTol: 378.5,
      maxTol: 381.5,
      unit: "mm",
      inspectionMethod: "Vernier Caliper / Fixture Gauge",
      sampleSize: 10,
      actualMeasured: "380.4 mm",
      status: "Pass",
    },
    {
      id: "char-3",
      seq: 3,
      characteristic: "Hi-Pot Electrical Insulation (Primary to Earth)",
      category: "Electrical",
      specification: "2,000 V AC for 60s, Leakage < 5.0 mA",
      nominal: 2000,
      minTol: 1950,
      maxTol: 2050,
      unit: "V",
      inspectionMethod: "Automated Hi-Pot Tester TST-005",
      sampleSize: 50,
      actualMeasured: "1.42 mA (Passed)",
      status: "Pass",
    },
    {
      id: "char-4",
      seq: 4,
      characteristic: "Ground Continuity Resistance",
      category: "Electrical",
      specification: "< 0.100 Ω at 25A test current",
      nominal: 0.05,
      minTol: 0.0,
      maxTol: 0.1,
      unit: "Ω",
      inspectionMethod: "Ground Bond Tester GB-101",
      sampleSize: 50,
      actualMeasured: "0.038 Ω",
      status: "Pass",
    },
    {
      id: "char-5",
      seq: 5,
      characteristic: "Pilot Signal Duty Cycle (IEC 61851-1)",
      category: "Functional",
      specification: "53.3% ± 1.0% (32A charging mode state B/C)",
      nominal: 53.3,
      minTol: 52.3,
      maxTol: 54.3,
      unit: "%",
      inspectionMethod: "EV Simulator Bench SIM-02",
      sampleSize: 50,
      actualMeasured: "53.2%",
      status: "Pass",
    },
    {
      id: "char-6",
      seq: 6,
      characteristic: "Terminal Lug Tightening Torque",
      category: "Dimensional",
      specification: "3.5 N·m ± 0.3 N·m",
      nominal: 3.5,
      minTol: 3.2,
      maxTol: 3.8,
      unit: "N·m",
      inspectionMethod: "Digital Calibrated Torque Wrench TW-04",
      sampleSize: 20,
      actualMeasured: "3.52 N·m",
      status: "Pass",
    },
    {
      id: "char-7",
      seq: 7,
      characteristic: "Emergency Stop Button Tripping Time",
      category: "Safety",
      specification: "< 100 ms disconnection response",
      nominal: 60,
      minTol: 0,
      maxTol: 100,
      unit: "ms",
      inspectionMethod: "High Speed Digital Oscilloscope",
      sampleSize: 50,
      actualMeasured: "48 ms",
      status: "Pass",
    },
  ],

  testSamples: [
    { sampleNo: 1, torqueReading: 3.48, insulationResistance: 480, leakageCurrent: 1.38 },
    { sampleNo: 2, torqueReading: 3.52, insulationResistance: 510, leakageCurrent: 1.41 },
    { sampleNo: 3, torqueReading: 3.55, insulationResistance: 495, leakageCurrent: 1.40 },
    { sampleNo: 4, torqueReading: 3.46, insulationResistance: 470, leakageCurrent: 1.45 },
    { sampleNo: 5, torqueReading: 3.50, insulationResistance: 530, leakageCurrent: 1.36 },
    { sampleNo: 6, torqueReading: 3.58, insulationResistance: 505, leakageCurrent: 1.42 },
    { sampleNo: 7, torqueReading: 3.51, insulationResistance: 490, leakageCurrent: 1.39 },
    { sampleNo: 8, torqueReading: 3.49, insulationResistance: 520, leakageCurrent: 1.43 },
    { sampleNo: 9, torqueReading: 3.54, insulationResistance: 515, leakageCurrent: 1.37 },
    { sampleNo: 10, torqueReading: 3.53, insulationResistance: 500, leakageCurrent: 1.40 },
  ],

  defects: [
    {
      id: "def-1",
      defectCode: "DC-001",
      category: "Visual",
      description: "Surface scratch on charging connector housing",
      quantity: 2,
      severity: "Major",
      disposition: "Rework",
      ncrReference: "NCR-2026-0047",
    },
  ],

  certificate: {
    certificateNo: "QC-2026-0142",
    issueDate: "08-Sep-2026",
    batchNo: "B-2026-09-014",
    productCode: "EVSE-7KW-001",
    productName: "Autonomous W-EVSE 7kW",
    quantityCertified: 48,
    authorizedSignatory: "Arun Kumar (Quality Assurance Lead)",
    digitalSealVerified: true,
    status: "Approved",
  },

  aiInsights: [
    {
      id: "ai-1",
      text: "Hi-pot test leakage current margin is within 15% of upper control limit on batch B-2026-09-014.",
      type: "alert",
    },
    {
      id: "ai-2",
      text: "Recommend thermal cycling validation before bulk palletizing for European export order.",
      type: "info",
    },
    {
      id: "ai-3",
      text: "Predicted dispatch compliance index: 98.6% based on passed serial history.",
      type: "success",
    },
  ],
};
