import { NcrRecord } from "./ncrTypes";

export const INITIAL_NCR_RECORD: NcrRecord = {
  // 1. Header
  ncrId: "ncr-rec-2026-0047",
  ncrNumber: "NCR-2026-0047",
  ncrDate: "06-Sep-2026 14:30",
  ncrSource: "In-Process Inspection",
  sourceReference: "IPQC-2026-00358",
  organization: "Magnertia Manufacturing Pvt. Ltd.",
  plant: "Chennai Plant",
  department: "Production",
  location: "Assembly Line 1",
  reportedBy: "Rajesh K",
  responsibleOwner: "Priya S",
  qualityEngineer: "Arun K",
  priority: "High",
  ncrStatus: "Open",
  dueDate: "20-Sep-2026",

  // 2. Non-Conformance Identification
  product: "Autonomous W-EVSE 7kW",
  productCode: "EVSE-7KW-001",
  productRevision: "REV-2.1",
  partComponent: "Charging Connector",
  batchLotNo: "B-2026-09-014",
  serialNumbers: "SN001, SN002, SN003",
  productionOrder: "MO-2026-00087",
  workOrder: "WO-2026-00421",
  operation: "OP-30",
  machineEquipment: "ASM-001",
  supplier: "- Select -",
  purchaseOrder: "-",
  grn: "-",
  customer: "GreenMobility Pvt. Ltd.",
  salesOrder: "SO-2026-0312",

  // 3. Problem Description
  nonConformanceTitle: "Surface scratch on charging connector housing",
  defectCategory: "Visual",
  defectCode: "DC-001",
  detectionMethod: "In-Process Inspection",
  problemDescription: "Multiple units show visible surface scratches on the charging connector housing.",
  requirementSpecification: "Housing surface shall be free from scratches, dents or cosmetic defects as per drawing DRW-EVSE-003.",
  detectionDate: "06-Sep-2026 14:15",
  detectionLocation: "Assembly Line 1",
  actualCondition: "Surface scratches observed on top cover near connector.",
  expectedCondition: "Clean surface finish without scratches.",
  affectedCharacteristic: "Housing Surface Finish",
  photos: [
    {
      id: "photo-1",
      filename: "IMG_20260906_01.jpg",
      fileSize: "2.4 MB",
      uploadDate: "06-Sep-2026 14:20",
      uploadedBy: "Rajesh K",
      hasRedCircle: true,
      caption: "Scratches on top cover near latch connector",
    },
    {
      id: "photo-2",
      filename: "IMG_20260906_02.jpg",
      fileSize: "1.8 MB",
      uploadDate: "06-Sep-2026 14:22",
      uploadedBy: "Rajesh K",
      caption: "Macro view of scratches on textured matte finish",
    },
    {
      id: "photo-3",
      filename: "IMG_20260906_03.jpg",
      fileSize: "3.1 MB",
      uploadDate: "06-Sep-2026 14:25",
      uploadedBy: "Rajesh K",
      caption: "Connector assembly nozzle orientation",
    },
  ],

  // 4. Severity & Risk Assessment
  severity: "Major",
  occurrenceScore: 6,
  detectionScore: 5,
  riskPriorityNumber: 180,
  riskLevel: "High",
  safetyImpact: false,
  customerImpact: true,
  regulatoryImpact: false,
  productionImpact: true,
  deliveryImpact: false,
  financialImpactEstimate: "₹45,000",
  escalationRequired: true,

  // 5. Immediate Containment
  containmentRequired: true,
  containmentStatus: "In Progress",
  containmentAction: "Segregated 50 units, stopped production, informed line supervisor.",
  affectedQuantity: 50,
  confirmedDefectQuantity: 2,
  suspectQuantity: 10,
  materialHold: true,
  wipHold: true,
  finishedGoodsHold: false,
  shipmentHold: false,
  customerNotification: false,
  supplierNotification: false,
  quarantineLocation: "QA Hold Area - A1",
  containmentOwner: "Priya S",
  containmentDate: "06-Sep-2026 15:00",

  // 7. Investigation
  investigationId: "INV-2026-0089",
  investigationLead: "Arun K",
  investigationStart: "06-Sep-2026 16:20",
  investigationEnd: "08-Sep-2026 11:30",
  investigationMethod: "5 Why",
  evidenceReviewed: "Physical samples SN001-SN003, conveyor belt surface, ASM-001 fixture locating pins, and operator handling trays.",
  processReviewed: "OP-30 Assembly & Cable Termination stage, transfer of molded housings from WIP tote to assembly fixture.",
  recordsReviewed: "IPQC log IPQC-2026-00358, tooling maintenance log for ASM-001, drawing DRW-EVSE-003 rev 2.1.",
  investigationFindings: "Burrs were identified on the left pneumatic holding fixture guide pin (ASM-001-P2). The pin rubbed against the top housing as units were loaded with force.",
  suspectedCause: "Worn fixture locator pin guide causing abrasion during manual alignment.",
  investigationStatus: "Open",

  // 8. Root Cause Analysis
  fiveWhys: [
    {
      level: 1,
      whyLabel: "Why 1",
      question: "Why did the defect occur?",
      answer: "Surface scratches appeared on the outer cover of the connector housing during assembly.",
    },
    {
      level: 2,
      whyLabel: "Why 2",
      question: "Why did that condition occur?",
      answer: "Fixture locator pin on machine ASM-001 rubbed against the plastic casing with excessive friction.",
    },
    {
      level: 3,
      whyLabel: "Why 3",
      question: "Why was the condition created?",
      answer: "Guide pin accumulated abrasive metal micro-burrs and lacked lubrication after continuous run cycles.",
    },
    {
      level: 4,
      whyLabel: "Why 4",
      question: "Why was it not prevented?",
      answer: "Daily pre-shift fixture visual check did not include a tactile burr inspection for guide pins.",
    },
    {
      level: 5,
      whyLabel: "Why 5",
      question: "Why was the system unable to prevent/detect it?",
      answer: "PM schedule did not track fixture stroke cycles automatically against the ERP production counter.",
    },
  ],
  ishikawaCauses: [
    { category: "Machine", title: "ASM-001 Fixture Locator Pin", notes: "Burrs on guide pin P2 due to wear (>4,000 cycles)", isContributing: true },
    { category: "Method", title: "Loading Procedure", notes: "Manual loading angle variation by operator during fast changeover", isContributing: true },
    { category: "Material", title: "Polycarbonate Housing", notes: "Material resin specification conforms to ASTM D638; not defective", isContributing: false },
    { category: "Man", title: "Operator Handling", notes: "Operator recently trained; need tactile inspection refresher", isContributing: true },
    { category: "Measurement", title: "Visual Inspection Lighting", notes: "Lux level at OP-30 inspection station is 850 lux (compliant)", isContributing: false },
    { category: "Environment", title: "Shop Floor Cleanliness", notes: "Dust control standard ISO Class 8 maintained", isContributing: false },
    { category: "Design", title: "Pin Clearance Tolerance", notes: "Guide pin clearance tolerance could be increased by 0.15mm", isContributing: false },
    { category: "Supplier", title: "Molded Shell Supplier", notes: "Shells delivered scratch-free from TechDrive Components", isContributing: false },
    { category: "System", title: "Preventive Maintenance Cycle", notes: "PM checklist missing tactile pin surface roughness check", isContributing: true },
  ],

  // 9. Corrective Action
  correctiveActions: [
    {
      id: "ca-1",
      actionId: "CA-2026-0094",
      rootCause: "Burrs on locator pin P2 of ASM-001",
      actionRequired: "Polish and de-burr locator pin P2; apply Teflon dry coating to eliminate abrasion.",
      actionType: "Process",
      owner: "Suresh M (Tooling)",
      targetDate: "08-Sep-2026",
      priority: "High",
      requiredResources: "Tool room technician, Teflon dry lubricant",
      estimatedCost: "₹2,500",
      completionDate: "07-Sep-2026",
      status: "Completed",
    },
    {
      id: "ca-2",
      actionId: "CA-2026-0095",
      rootCause: "Pre-shift inspection checklist gap",
      actionRequired: "Update daily pre-shift tooling checklist SOP-PRD-012 to mandate tactile feeling and pin cleanliness check.",
      actionType: "System",
      owner: "Priya S (Quality)",
      targetDate: "10-Sep-2026",
      priority: "Medium",
      requiredResources: "Document control update, training sheet",
      estimatedCost: "₹1,000",
      status: "In Progress",
    },
    {
      id: "ca-3",
      actionId: "CA-2026-0096",
      rootCause: "Operator loading technique variation",
      actionRequired: "Conduct 15-minute one-point lesson (OPL) for all Line 1 operators on ergonomic connector seating.",
      actionType: "Product",
      owner: "Rajesh K (Supervisor)",
      targetDate: "09-Sep-2026",
      priority: "Medium",
      requiredResources: "Training kiosk, OPL visual aid",
      estimatedCost: "₹500",
      status: "In Progress",
    },
  ],

  // 10. CAPA
  isSystemicCause: true,
  relatedCapaId: undefined, // Not yet created, shows "Create CAPA ->"
  capaStatus: "Not Created",

  // 11. Disposition
  dispositionType: "Rework",
  dispositionNotes: "50 segregated units: 40 conforming units released to production, 10 suspect units inspected. 2 units with scratches scheduled for top cover replacement. 8 units passed cosmetic inspection.",
  dispositionApprovedBy: "Priya S",
  dispositionDate: "06-Sep-2026 17:00",

  // 12. Rework & Re-Inspection
  reworkOrder: "RW-2026-0018",
  reworkOperation: "RW-OP-01 (Cover Disassembly & Replacement)",
  reworkInstruction: "WI-RW-004",
  reworkQuantity: 2,
  reworkCompletedBy: "Murugan V",
  reworkDate: "07-Sep-2026 10:00",
  reInspectionRequired: true,
  reInspectionNo: "RE-IPQC-0042",
  reInspectionResult: "Pass",
  finalQualityApproval: "Arun K (QE)",

  // 13. Verification
  verifications: [
    {
      id: "ver-1",
      verificationId: "VR-2026-0031",
      method: "Inspection",
      date: "08-Sep-2026",
      verifiedBy: "Arun K",
      result: "Effective",
      residualRiskScore: 36,
      additionalAction: "Monitor next 3 consecutive shifts for any cosmetic defects on Line 1.",
    },
  ],

  // 14. Closure
  closureRecommendation: "Close NCR upon completing operator training and 3-shift defect-free run.",
  closureDate: "20-Sep-2026",
  closureVerifiedBy: "Arun K",
  qualityManagerApproval: "Pending",
  effectivenessResult: "Pending Review",
  ncrClosureStatus: "Open",
  closureRemarks: "Immediate containment successful. Rework executed for 2 affected units. CAPA pending systemic review.",

  // Connected widgets & activities
  recentActivities: [
    {
      id: "act-1",
      action: "NCR created",
      timestamp: "06-Sep-2026 14:30",
      user: "Rajesh K",
      details: "Initial NCR raised from In-Process Inspection IPQC-2026-00358",
    },
    {
      id: "act-2",
      action: "Containment action updated",
      timestamp: "06-Sep-2026 15:00",
      user: "Priya S",
      details: "Segregated 50 units, stopped production, informed line supervisor",
    },
    {
      id: "act-3",
      action: "Assigned to Quality Engineer",
      timestamp: "06-Sep-2026 15:05",
      user: "System",
      details: "Auto-assigned to Arun K based on Line 1 ownership",
    },
    {
      id: "act-4",
      action: "Investigation started",
      timestamp: "06-Sep-2026 16:20",
      user: "Arun K",
      details: "Investigation initiated using 5-Why root cause methodology",
    },
  ],

  aiInsights: [
    {
      id: "ai-1",
      type: "alert",
      title: "Recurrence Pattern",
      description: "Similar visual defects found in last 3 batches from same operation.",
      severity: "high",
    },
    {
      id: "ai-2",
      type: "root_cause",
      title: "Root Cause Hypothesis",
      description: "Possible root cause: improper handling or fixture misalignment.",
      severity: "medium",
    },
    {
      id: "ai-3",
      type: "recommendation",
      title: "Preventive Recommendation",
      description: "Recommend immediate process audit and operator re-training.",
      severity: "info",
    },
    {
      id: "ai-4",
      type: "risk",
      title: "Recurrence Risk Index",
      description: "Estimated risk of recurrence: 32% (Medium).",
      severity: "low",
    },
  ],
};
