import { QualityAnalyticsDataset } from "./qualityAnalyticsTypes";

export const INITIAL_ANALYTICS_DATASET: QualityAnalyticsDataset = {
  filters: {
    dateFrom: "01-Aug-2026",
    dateTo: "06-Sep-2026",
    plant: "All Plants",
    department: "All Departments",
    process: "All Processes",
    product: "All Products",
    productFamily: "All",
    supplier: "All Suppliers",
    customer: "All Customers",
    machine: "All Machines",
    shift: "All Shifts",
    qualityCategory: "All",
    defectCategory: "All",
  },

  executiveKpis: [
    {
      id: "kpi-1",
      label: "Overall Quality Score",
      value: "94.2%",
      target: "Target: ≥ 95%",
      trend: "↑ 2.1%",
      trendDirection: "up",
      trendColor: "green",
      status: "warning",
      iconName: "Medal",
      color: "text-blue-600",
    },
    {
      id: "kpi-2",
      label: "First Pass Yield",
      value: "92.3%",
      target: "Target: ≥ 95%",
      trend: "↓ 1.8%",
      trendDirection: "down",
      trendColor: "red",
      status: "warning",
      iconName: "BarChart3",
      color: "text-blue-600",
    },
    {
      id: "kpi-3",
      label: "Defect Rate",
      value: "2.8%",
      target: "Target: ≤ 2.0%",
      trend: "↓ 0.6%",
      trendDirection: "down",
      trendColor: "green",
      status: "warning",
      iconName: "AlertTriangle",
      color: "text-rose-600",
    },
    {
      id: "kpi-4",
      label: "Scrap Rate",
      value: "1.2%",
      target: "Target: ≤ 1.0%",
      trend: "↓ 0.2%",
      trendDirection: "down",
      trendColor: "green",
      status: "warning",
      iconName: "Trash2",
      color: "text-rose-600",
    },
    {
      id: "kpi-5",
      label: "Rework Rate",
      value: "2.1%",
      target: "Target: ≤ 2.0%",
      trend: "↓ 0.4%",
      trendDirection: "down",
      trendColor: "green",
      status: "warning",
      iconName: "RefreshCw",
      color: "text-blue-600",
    },
    {
      id: "kpi-6",
      label: "NCRs",
      value: "47",
      target: "Target: ≤ 40",
      trend: "↓ 20%",
      trendDirection: "down",
      trendColor: "green",
      status: "warning",
      iconName: "FileText",
      color: "text-blue-600",
    },
    {
      id: "kpi-7",
      label: "CAPA Closure Rate",
      value: "91.9%",
      target: "Target: ≥ 95%",
      trend: "↑ 3.2%",
      trendDirection: "up",
      trendColor: "green",
      status: "warning",
      iconName: "CheckCircle2",
      color: "text-emerald-600",
    },
  ],

  defectTrend6Months: [
    { month: "Mar", defectRate: 4.2, target: 2.0 },
    { month: "Apr", defectRate: 3.8, target: 2.0 },
    { month: "May", defectRate: 3.1, target: 2.0 },
    { month: "Jun", defectRate: 2.9, target: 2.0 },
    { month: "Jul", defectRate: 2.6, target: 2.0 },
    { month: "Aug", defectRate: 2.8, target: 2.0 },
    { month: "Sep", defectRate: 2.8, target: 2.0 },
  ],

  defectPareto: [
    { rank: 1, defect: "Assembly Error", count: 38, percentage: 31, cumulativePercentage: 31 },
    { rank: 2, defect: "Surface Defect", count: 27, percentage: 22, cumulativePercentage: 53 },
    { rank: 3, defect: "Electrical Failure", count: 21, percentage: 17, cumulativePercentage: 70 },
    { rank: 4, defect: "Dimensional Error", count: 16, percentage: 13, cumulativePercentage: 83 },
    { rank: 5, defect: "Material Defect", count: 12, percentage: 10, cumulativePercentage: 93 },
    { rank: 6, defect: "Connector Issue", count: 5, percentage: 4, cumulativePercentage: 97 },
    { rank: 7, defect: "Cosmetic Defect", count: 3, percentage: 2, cumulativePercentage: 99 },
    { rank: 8, defect: "Software Issue", count: 1, percentage: 1, cumulativePercentage: 100 },
  ],

  processPerformance: [
    { process: "Assembly", fpy: 94.1, defectRate: 2.4, rework: 1.8, scrap: 0.7, qualityScore: 95.0 },
    { process: "Electrical Test", fpy: 93.8, defectRate: 2.9, rework: 2.1, scrap: 0.8, qualityScore: 94.2 },
    { process: "Functional Test", fpy: 95.4, defectRate: 2.1, rework: 1.4, scrap: 0.5, qualityScore: 96.1 },
    { process: "Packaging", fpy: 97.0, defectRate: 1.6, rework: 0.8, scrap: 0.2, qualityScore: 97.5 },
  ],

  supplierQuality: [
    { supplier: "Supplier A", lots: 36, defects: 11, ppm: 2140, rejectionPercent: 3.2, qualityScore: 94.5, status: "High" },
    { supplier: "Supplier B", lots: 42, defects: 6, ppm: 1020, rejectionPercent: 1.5, qualityScore: 97.2, status: "High" },
    { supplier: "Supplier C", lots: 31, defects: 14, ppm: 3420, rejectionPercent: 4.6, qualityScore: 91.8, status: "Medium" },
    { supplier: "Supplier D", lots: 28, defects: 7, ppm: 1850, rejectionPercent: 2.5, qualityScore: 95.6, status: "High" },
    { supplier: "Supplier E", lots: 24, defects: 9, ppm: 2960, rejectionPercent: 3.8, qualityScore: 93.1, status: "Medium" },
  ],

  aiInsights: [
    {
      id: "ai-1",
      category: "alert",
      text: "Defect rate increased by 12% in Assembly (last 2 weeks).",
      severity: "critical",
    },
    {
      id: "ai-2",
      category: "alert",
      text: "Surface defect is the top contributor (22%).",
      severity: "high",
    },
    {
      id: "ai-3",
      category: "warning",
      text: "Supplier C shows higher rejection rate (4.6%).",
      severity: "medium",
    },
    {
      id: "ai-4",
      category: "success",
      text: "CAPA effectiveness improved to 91.9%.",
      severity: "positive",
    },
    {
      id: "ai-5",
      category: "root-cause",
      text: "Potential root cause: Inadequate torque control (based on similar NCRs).",
      severity: "high",
    },
    {
      id: "ai-6",
      category: "recommendation",
      text: "Recommend: Review assembly fixture and operator training.",
      severity: "medium",
    },
  ],

  spcParameters: [
    {
      parameter: "Torque (Nm)",
      mean: 10.02,
      ucl: 10.50,
      lcl: 9.50,
      cp: 1.42,
      cpk: 1.31,
      status: "Stable",
      history: [10.01, 10.04, 9.98, 10.02, 10.05, 10.01, 9.99, 10.03, 10.02],
    },
    {
      parameter: "Voltage (V)",
      mean: 230.2,
      ucl: 235.0,
      lcl: 225.0,
      cp: 1.58,
      cpk: 1.47,
      status: "Stable",
      history: [230.1, 230.4, 229.8, 230.2, 230.6, 230.1, 229.9, 230.3, 230.2],
    },
    {
      parameter: "Temperature (°C)",
      mean: 42.8,
      ucl: 45.0,
      lcl: 35.0,
      cp: 1.18,
      cpk: 1.05,
      status: "Warning",
      history: [41.2, 41.8, 42.1, 42.9, 43.4, 43.8, 44.1, 43.5, 42.8],
    },
  ],

  copqComponents: [
    { category: "Scrap", element: "Scrap", amount: 480000, percentage: 31.8, classification: "Internal Failure" },
    { category: "Rework", element: "Rework", amount: 320000, percentage: 21.2, classification: "Internal Failure" },
    { category: "Inspection & Testing", element: "Inspection & Testing", amount: 140000, percentage: 9.3, classification: "Appraisal" },
    { category: "Warranty Claims", element: "Warranty Claims", amount: 210000, percentage: 13.9, classification: "External Failure" },
    { category: "Customer Returns", element: "Customer Returns", amount: 160000, percentage: 10.6, classification: "External Failure" },
    { category: "Customer Complaints Handling", element: "Customer Complaints Handling", amount: 80000, percentage: 5.3, classification: "External Failure" },
    { category: "Supplier Quality Loss", element: "Supplier Quality Loss", amount: 120000, percentage: 7.9, classification: "Internal Failure" },
  ],

  actionTracker: [
    {
      id: "act-1",
      action: "Fixture improvement & pneumatic clamping calibration",
      source: "NCR-2026-0089",
      owner: "Production Engineering",
      department: "Manufacturing",
      dueDate: "12-Sep-2026",
      priority: "High",
      status: "In Progress",
    },
    {
      id: "act-2",
      action: "Operator retraining on torque tool handling",
      source: "CAPA-2026-0012",
      owner: "HR & QA Training Cell",
      department: "Human Resources",
      dueDate: "15-Sep-2026",
      priority: "Medium",
      status: "Open",
    },
    {
      id: "act-3",
      action: "Supplier process audit on connector pin plating thickness",
      source: "Supplier NCR-041",
      owner: "Senior Supplier Quality Engineer",
      department: "Supplier Quality",
      dueDate: "18-Sep-2026",
      priority: "High",
      status: "Open",
    },
    {
      id: "act-4",
      action: "Test procedure update for wave soldering thermal profiling",
      source: "RCA-2026-0012",
      owner: "Lead Quality Systems Engineer",
      department: "Quality Assurance",
      dueDate: "20-Sep-2026",
      priority: "Medium",
      status: "Planned",
    },
  ],
};
