import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client.js";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

type SeedModule = {
  moduleType: string;
  recordCode: string;
  formCode: string;
  projectName: string;
  version: string;
  workflowStatus: string;
  stage: number;
  priority: string;
  ownerName: string;
  ownerEmail?: string;
  businessUnit?: string;
  department?: string;
  overallScore: number;
  recommendation: string;
  approvalDecision?: string;
  formData: Record<string, any>;
  sectionScores: Record<string, number>;
  aiAssessment: Record<string, any>;
  reviewers: { role: string; person: string; decision: string; status: string; comments: string }[];
  attachments: { fileName: string; fileType: string; documentType: string; uploadedBy: string; fileSize: string }[];
  activities: { user: string; action: string; description: string }[];
};

const SEED_MODULES: SeedModule[] = [
  {
    moduleType: "automation-development",
    recordCode: "APD-2024-00045",
    formCode: "APDF-2024-25",
    projectName: "Automated Battery Assembly & Testing Cell",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 3,
    priority: "High",
    ownerName: "Vikram Singh",
    businessUnit: "Smart Mobility Division",
    department: "Manufacturing Engineering",
    overallScore: 84,
    recommendation: "Approve Automation Project",
    approvalDecision: "Approved",
    formData: {
      automationProjectTitle: "Automated Battery Assembly & Testing Cell",
      projectNumber: "AP-BA-24-001",
      productProcess: "Battery Assembly",
      manufacturingPlant: "Plant-01",
      productionLine: "Battery Assembly Line-02",
      automationEngineer: "Vikram Singh",
      automationCategory: "Industrial Robotics",
      automationObjective: "Automate battery module assembly and testing to improve productivity and quality.",
      cycleTimeCurrentSec: 120.0,
      cycleTimeTargetSec: 75.0,
      automationPotential: 88,
      roiEstimateInr: 487500000,
      iiotConnectivity: "Connected",
      cybersecurityValidation: "Validated",
      fatCompleted: true,
      satCompleted: true,
      oeeImprovementPct: 22.5,
      installationStatus: "Installed",
    },
    sectionScores: { processReadinessScore: 82, developmentScore: 88, validationScore: 85, commissioningScore: 79, productivityScore: 88, qualityImprovementScore: 86, costSavingScore: 84, energyEfficiencyScore: 82 },
    aiAssessment: { aiProcessOptimization: "AI suggests optimizing robot path and reducing motion time by 12%.", aiAutomationHealthScore: 86 },
    reviewers: [
      { role: "Automation Engineer", person: "Vikram Singh", decision: "Approved", status: "Approved", comments: "Cell integration verified." },
      { role: "Controls Engineer", person: "Neha Reddy", decision: "Approved", status: "Approved", comments: "PLC logic & safety interlocks validated." },
      { role: "Plant Head", person: "Sankaran R.", decision: "Pending", status: "Pending", comments: "" },
    ],
    attachments: [
      { fileName: "Automation Architecture.pdf", fileType: "PDF", documentType: "Architecture", uploadedBy: "Vikram Singh", fileSize: "4.2 MB" },
    ],
    activities: [
      { user: "Rahul Sharma", action: "Record Created", description: "Created Automation Development record APD-2024-00045." },
      { user: "Vikram Singh", action: "Hardware Platforms Selected", description: "Selected Siemens S7-1500, ABB IRB 1200, Cognex In-Sight 7800." },
    ],
  },
  {
    moduleType: "bom-engineering",
    recordCode: "BOM-2024-00125",
    formCode: "BOMD-2024-25",
    projectName: "Autonomous W-EVSE - Engineering BOM",
    version: "2.1",
    workflowStatus: "In Review",
    stage: 4,
    priority: "High",
    ownerName: "Rahul Sharma",
    businessUnit: "Smart Mobility Division",
    overallScore: 89,
    recommendation: "Approve BOM",
    approvalDecision: "Approved with Conditions",
    formData: {
      bomName: "Autonomous W-EVSE - Engineering BOM",
      bomNumber: "EBOM-AW-EVSE-001",
      product: "Autonomous W-EVSE",
      bomType: "Engineering BOM (EBOM)",
      processOwner: "Rahul Sharma",
      totalItemsCount: 86,
      totalBomCost: 245680,
      targetCost: 260000,
      costVariance: -14320,
      lifecycleStage: "Engineering Validation",
    },
    sectionScores: { completenessScore: 92, materialAvailabilityScore: 88, manufacturingReadinessScore: 90, qualityReadinessScore: 86, costScore: 87, overallReadinessScore: 89 },
    aiAssessment: { duplicateDetection: "No duplicate components found.", healthScore: 91 },
    reviewers: [
      { role: "Design Engineer", person: "Rahul Sharma", decision: "Approved", status: "Approved", comments: "BOM structure matches CAD Release 2.1." },
      { role: "COO", person: "Arvind Swaminathan", decision: "Approved", status: "Approved", comments: "Final executive approval granted." },
    ],
    attachments: [
      { fileName: "EBOM-AW-EVSE-001_v2.1.xlsx", fileType: "Spreadsheet", documentType: "Engineering BOM", uploadedBy: "Rahul Sharma", fileSize: "2.4 MB" },
    ],
    activities: [
      { user: "Rahul Sharma", action: "Create BOM Project", description: "Created Engineering BOM project BOM-2024-00125." },
    ],
  },
  {
    moduleType: "mechanical-design",
    recordCode: "MD-2024-0017",
    formCode: "MDF-2024-25",
    projectName: "Smart EV Charger – Mechanical Design",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Rahul Sharma",
    businessUnit: "Smart Mobility Division",
    overallScore: 86,
    recommendation: "Approve with Minor Revisions",
    formData: {
      designProjectName: "Smart EV Charger – Mechanical Design",
      designVersion: "v1.0",
      status: "Under Review",
      currentStage: "engineering_review",
      currentStageLabel: "Stage 4: Engineering Review",
      mechanicalEngineerName: "Rahul Sharma",
      stages: [
        { id: "mechanical_engineering_design", label: "Stage 1", stageNumber: 1, status: "completed" },
        { id: "material_manufacturing_validation", label: "Stage 2", stageNumber: 2, status: "completed" },
        { id: "simulation_validation", label: "Stage 3", stageNumber: 3, status: "completed" },
        { id: "engineering_review", label: "Stage 4", stageNumber: 4, status: "in_progress" },
      ],
      input: { productName: "Smart EV Charger", designMethodology: "Design for Manufacturing (DFM)", numberOfComponents: 125 },
    },
    sectionScores: { structuralReadiness: 88, manufacturability: 86, reliability: 85, simulation: 84 },
    aiAssessment: { aiDesignQuality: 87, aiManufacturability: 86, aiStructuralAssessment: 90, aiCostOptimization: 84 },
    reviewers: [],
    attachments: [],
    activities: [
      { user: "Rahul Sharma", action: "Record Created", description: "Mechanical Design record created." },
    ],
  },
  {
    moduleType: "electrical-design",
    recordCode: "ED-2024-0017",
    formCode: "EDF-2024-25",
    projectName: "Smart EV Charger – Electrical Design",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Ananya Iyer",
    businessUnit: "Smart Mobility Division",
    overallScore: 87,
    recommendation: "Approve with Minor Revisions",
    formData: {
      designProjectName: "Smart EV Charger – Electrical Design",
      designVersion: "v1.0",
      status: "Under Review",
      currentStage: "engineering_review",
      electricalEngineerName: "Ananya Iyer",
      stages: [
        { id: "electrical_architecture", label: "Stage 1", stageNumber: 1, status: "completed" },
        { id: "circuit_pcb_design", label: "Stage 2", stageNumber: 2, status: "completed" },
        { id: "simulation_validation", label: "Stage 3", stageNumber: 3, status: "completed" },
        { id: "engineering_review", label: "Stage 4", stageNumber: 4, status: "in_progress" },
      ],
      input: { productName: "Smart EV Charger", pcbLayerCount: 8 },
    },
    sectionScores: { powerSystemReadiness: 88, circuitReadiness: 85, electricalSafetyScore: 88, complianceScore: 85 },
    aiAssessment: { aiOverallElectricalScore: 87, aiDesignQualityScore: 89 },
    reviewers: [],
    attachments: [],
    activities: [
      { user: "Ananya Iyer", action: "Record Created", description: "Electrical Design record created." },
    ],
  },
  {
    moduleType: "firmware-development",
    recordCode: "FWD-2024-0017",
    formCode: "FWF-2024-25",
    projectName: "Smart EV Charger – Firmware Development",
    version: "2.1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Rajesh Varma",
    businessUnit: "Smart Mobility Division",
    overallScore: 91,
    recommendation: "Approve for Production",
    formData: {
      firmwareProjectName: "Smart EV Charger – Firmware Development",
      firmwareVersion: "v2.1.0",
      status: "Under Review",
      currentStage: "engineering_review",
      firmwareLeadName: "Rajesh Varma",
      stages: [
        { id: "firmware_architecture_implementation", label: "Stage 1", stageNumber: 1, status: "completed" },
        { id: "communication_security", label: "Stage 2", stageNumber: 2, status: "completed" },
        { id: "testing_release", label: "Stage 3", stageNumber: 3, status: "completed" },
        { id: "engineering_review", label: "Stage 4", stageNumber: 4, status: "in_progress" },
      ],
      input: { productName: "Smart EV Charger", codeCoverage: 94.6 },
    },
    sectionScores: { firmwareReadiness: 90, codeQuality: 92, securityReadiness: 92, testCoverage: 95 },
    aiAssessment: { aiOverallFirmwareScore: 91, aiCodeQualityScore: 92 },
    reviewers: [],
    attachments: [],
    activities: [
      { user: "Rajesh Varma", action: "Record Created", description: "Firmware Development record created." },
    ],
  },
  {
    moduleType: "electronics-design",
    recordCode: "EN-2024-0017",
    formCode: "EDF-2024-25",
    projectName: "Smart EV Charger – Electronics Design",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Rohit Nair",
    businessUnit: "Smart Mobility Division",
    overallScore: 86,
    recommendation: "Approve with Minor Revisions",
    formData: { designProjectName: "Smart EV Charger – Electronics Design", electronicsEngineerName: "Rohit Nair" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rohit Nair", action: "Record Created", description: "Electronics Design record created." }],
  },
  {
    moduleType: "embedded-development",
    recordCode: "EMD-2024-0017",
    formCode: "EMF-2024-25",
    projectName: "Smart EV Charger – Embedded Systems Development",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Kavita Sharma",
    businessUnit: "Smart Mobility Division",
    overallScore: 88,
    recommendation: "Approve with Minor Revisions",
    formData: { developmentProjectName: "Smart EV Charger – Embedded Systems Development", embeddedEngineerName: "Kavita Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Kavita Sharma", action: "Record Created", description: "Embedded Systems Development record created." }],
  },
  {
    moduleType: "industrial-design",
    recordCode: "ID-2024-0017",
    formCode: "IDF-2024-25",
    projectName: "Smart EV Charger - Industrial Design",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Rohit Verma",
    overallScore: 85,
    recommendation: "Approve with Minor Revisions",
    formData: { designProjectName: "Smart EV Charger - Industrial Design", industrialDesignerName: "Rohit Verma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rohit Verma", action: "Record Created", description: "Industrial Design record created." }],
  },
  {
    moduleType: "mobile-development",
    recordCode: "MAD-2024-0017",
    formCode: "MAF-2024-25",
    projectName: "Magnertia EV Charger App",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 84,
    recommendation: "Approve with Minor Revisions",
    formData: { mobileProjectName: "Magnertia EV Charger App", mobileArchitectName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Mobile Development record created." }],
  },
  {
    moduleType: "software-development",
    recordCode: "SWD-2024-0017",
    formCode: "SWF-2024-25",
    projectName: "Smart EV Management Platform",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 87,
    recommendation: "Approve with Minor Revisions",
    formData: { softwareProjectName: "Smart EV Management Platform", softwareArchitectName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Software Development record created." }],
  },
  {
    moduleType: "ai-model-development",
    recordCode: "AIMD-2024-0018",
    formCode: "AMDF-2024-25",
    projectName: "EV Demand Forecasting Model",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 82,
    recommendation: "Approve with Minor Revisions",
    formData: { aiProjectName: "EV Demand Forecasting Model", aiLeadEngineerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "AI Model Development record created." }],
  },
  {
    moduleType: "api-development",
    recordCode: "API-2024-0017",
    formCode: "APF-2024-25",
    projectName: "EV Charging APIs",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 83,
    recommendation: "Approve with Minor Revisions",
    formData: { apiProjectName: "EV Charging APIs", apiArchitectName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "API Development record created." }],
  },
  {
    moduleType: "cloud-platform-development",
    recordCode: "CLD-2024-0001",
    formCode: "CLD-F-2024-25",
    projectName: "Magnertia Cloud Platform",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 85,
    recommendation: "Approve with Minor Revisions",
    formData: { cloudProjectName: "Magnertia Cloud Platform", cloudArchitectName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Cloud Platform Development record created." }],
  },
  {
    moduleType: "cybersecurity-engineering",
    recordCode: "CSE-2024-0018",
    formCode: "CSEF-2024-25",
    projectName: "Smart EV Charging Security",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 84,
    recommendation: "Approve with Minor Revisions",
    formData: { securityProjectName: "Smart EV Charging Security", securityArchitectName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Cybersecurity Engineering record created." }],
  },
  {
    moduleType: "iot-development",
    recordCode: "IOT-2024-0009",
    formCode: "IOTF-2024-25",
    projectName: "Smart EV Charging Network",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 86,
    recommendation: "Approve with Minor Revisions",
    formData: { iotProjectName: "Smart EV Charging Network", iotArchitectName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "IoT Development record created." }],
  },
  {
    moduleType: "uiux-development",
    recordCode: "UIUX-2024-0017",
    formCode: "UIUX-F-2024-25",
    projectName: "Smart EV Charger UI/UX",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 83,
    recommendation: "Approve with Minor Revisions",
    formData: { uiUxProjectName: "Smart EV Charger UI/UX", designerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "UI/UX Development record created." }],
  },
  {
    moduleType: "simulation-analysis",
    recordCode: "SIM-2024-0027",
    formCode: "SIMF-2024-25",
    projectName: "W-EVSE Thermal & Structural Analysis",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 85,
    recommendation: "Approve with Minor Revisions",
    formData: { simulationProjectName: "W-EVSE Thermal & Structural Analysis", simulationEngineerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Simulation Analysis record created." }],
  },
  {
    moduleType: "plm",
    recordCode: "PLM-2024-0021",
    formCode: "PLMF-2024-25",
    projectName: "Smart EV Charger PLM",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 84,
    recommendation: "Approve with Minor Revisions",
    formData: { plmProjectName: "Smart EV Charger PLM", productOwnerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "PLM record created." }],
  },
  {
    moduleType: "prd",
    recordCode: "PRD-2024-0017",
    formCode: "PRD-2024-08",
    projectName: "Smart EV Charger Pro – v2.3 Wireless & RFID Module PRD",
    version: "2.3",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Vikram Sharma",
    overallScore: 86,
    recommendation: "Approve with Minor Revisions",
    formData: { prdTitle: "Smart EV Charger Pro – v2.3 Wireless & RFID Module PRD", productOwnerName: "Vikram Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Sharma", action: "Record Created", description: "PRD record created." }],
  },
  {
    moduleType: "product-architecture",
    recordCode: "PA-2024-0017",
    formCode: "PA-2024-25",
    projectName: "Smart EV Charger Architecture",
    version: "1.0",
    workflowStatus: "Under Review",
    stage: 4,
    priority: "High",
    ownerName: "Rohit Verma",
    overallScore: 85,
    recommendation: "Approve with Minor Revisions",
    formData: { architectureName: "Smart EV Charger Architecture", systemArchitectName: "Rohit Verma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rohit Verma", action: "Record Created", description: "Product Architecture record created." }],
  },
  {
    moduleType: "product-documentation",
    recordCode: "DOC-2024-0087",
    formCode: "DOF-2024-25",
    projectName: "Smart EV Charger Documentation",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "Medium",
    ownerName: "Rahul Sharma",
    overallScore: 78,
    recommendation: "Revisions Required",
    formData: { documentationProject: "Smart EV Charger Documentation", documentOwnerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Product Documentation record created." }],
  },
  {
    moduleType: "product-release",
    recordCode: "REL-2024-0053",
    formCode: "RLF-2024-25",
    projectName: "Smart EV Charger Launch",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 80,
    recommendation: "Approve with Minor Revisions",
    formData: { releaseProjectName: "Smart EV Charger Launch", releaseManagerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Product Release record created." }],
  },
  {
    moduleType: "product-roadmap",
    recordCode: "PRM-2024-0017",
    formCode: "PRM-2024-08",
    projectName: "Smart EV Charger Pro Product Roadmap (2024-2027)",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Vikram Sharma",
    overallScore: 84,
    recommendation: "Approve with Minor Revisions",
    formData: { roadmapName: "Smart EV Charger Pro Product Roadmap (2024-2027)", productManagerName: "Vikram Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Sharma", action: "Record Created", description: "Product Roadmap record created." }],
  },
  {
    moduleType: "product-strategy",
    recordCode: "PS-2024-0017",
    formCode: "PS-2024-08",
    projectName: "Smart EV Charger Pro Strategy 2024-2027",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Vikram Sharma",
    overallScore: 83,
    recommendation: "Approve with Minor Revisions",
    formData: { strategyName: "Smart EV Charger Pro Strategy 2024-2027", productManagerName: "Vikram Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Sharma", action: "Record Created", description: "Product Strategy record created." }],
  },
  {
    moduleType: "testing-validation",
    recordCode: "TV-2024-0075",
    formCode: "TVF-2024-25",
    projectName: "Smart EV Charger Validation",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 82,
    recommendation: "Approve with Minor Revisions",
    formData: { testProjectName: "Smart EV Charger Validation", testEngineerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Testing Validation record created." }],
  },
  {
    moduleType: "certification-readiness",
    recordCode: "CR-2024-0041",
    formCode: "CRF-2024-25",
    projectName: "Smart EV Charger Certification",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 81,
    recommendation: "Approve with Minor Revisions",
    formData: { certificationProjectName: "Smart EV Charger Certification", complianceManagerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Certification Readiness record created." }],
  },
  {
    moduleType: "apqp",
    recordCode: "APQP-2024-00056",
    formCode: "AQPL-2024-25",
    projectName: "Autonomous W-EVSE Quality Program",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 84,
    recommendation: "Approve with Minor Revisions",
    formData: { apqpProjectName: "Autonomous W-EVSE Quality Program", projectManager: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "APQP record created." }],
  },
  {
    moduleType: "assembly-line-development",
    recordCode: "ASM-2024-0045",
    formCode: "ALDF-2024-25",
    projectName: "Smart EV Charger Assembly Line",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 82,
    recommendation: "Approve with Minor Revisions",
    formData: { projectName: "Smart EV Charger Assembly Line", assemblyLineEngineerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Assembly Line Development record created." }],
  },
  {
    moduleType: "control-plan",
    recordCode: "CP-2024-00056",
    formCode: "CPDL-2024-25",
    projectName: "Enclosure Assembly Control Plan",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 83,
    recommendation: "Approve with Minor Revisions",
    formData: { controlPlanTitle: "Enclosure Assembly Control Plan", processOwner: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Control Plan record created." }],
  },
  {
    moduleType: "fixture-development",
    recordCode: "FIX-2024-0056",
    formCode: "FDF-2024-25",
    projectName: "EV Charger Assembly Fixture",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 80,
    recommendation: "Approve with Minor Revisions",
    formData: { projectName: "EV Charger Assembly Fixture", createdBy: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Fixture Development record created." }],
  },
  {
    moduleType: "lean-manufacturing",
    recordCode: "LEAN-2024-00123",
    formCode: "LMRF-2024-25",
    projectName: "Reduce Changeover Time in Assembly Line",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Vikram Singh",
    overallScore: 82,
    recommendation: "Approve with Minor Revisions",
    formData: { leanProjectTitle: "Reduce Changeover Time in Assembly Line", processOwner: "Vikram Singh" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Singh", action: "Record Created", description: "Lean Manufacturing record created." }],
  },
  {
    moduleType: "manufacturing-excellence",
    recordCode: "MEX-2024-00045",
    formCode: "MEXF-2024-25",
    projectName: "OEE Improvement & Cost Optimization Initiative",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 81,
    recommendation: "Approve with Minor Revisions",
    formData: { initiativeTitle: "OEE Improvement & Cost Optimization Initiative", processOwner: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Manufacturing Excellence record created." }],
  },
  {
    moduleType: "mass-production-readiness",
    recordCode: "RDR-2024-00056",
    formCode: "MPRF-2024-25",
    projectName: "Autonomous W-EVSE Mass Production Readiness",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Vikram Singh",
    overallScore: 80,
    recommendation: "Approve with Minor Revisions",
    formData: { readinessTitle: "Autonomous W-EVSE Mass Production Readiness", processOwner: "Vikram Singh" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Singh", action: "Record Created", description: "Mass Production Readiness record created." }],
  },
  {
    moduleType: "pfmea",
    recordCode: "PFMEA-2024-00078",
    formCode: "PFMEA-2024-25",
    projectName: "Enclosure Assembly Process PFMEA",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 83,
    recommendation: "Approve with Minor Revisions",
    formData: { pfmeaTitle: "Enclosure Assembly Process PFMEA", processOwner: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "PFMEA record created." }],
  },
  {
    moduleType: "pilot-production",
    recordCode: "PILOT-2024-00078",
    formCode: "PPFD-2024-25",
    projectName: "Autonomous W-EVSE Pilot Production",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Vikram Singh",
    overallScore: 79,
    recommendation: "Revisions Required",
    formData: { pilotBatchTitle: "Autonomous W-EVSE Pilot Production", processOwner: "Vikram Singh" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Singh", action: "Record Created", description: "Pilot Production record created." }],
  },
  {
    moduleType: "process-validation",
    recordCode: "PV-2024-00078",
    formCode: "PVDF-2024-25",
    projectName: "Enclosure Assembly Process Validation",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 82,
    recommendation: "Approve with Minor Revisions",
    formData: { validationTitle: "Enclosure Assembly Process Validation", processOwner: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Process Validation record created." }],
  },
  {
    moduleType: "production-engineering",
    recordCode: "PE-2024-0056",
    formCode: "PEF-2024-25",
    projectName: "Smart EV Charger Production",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 81,
    recommendation: "Approve with Minor Revisions",
    formData: { projectName: "Smart EV Charger Production", productionEngineerName: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Production Engineering record created." }],
  },
  {
    moduleType: "robotics-integration",
    recordCode: "RIP-2024-00035",
    formCode: "RPF-2024-25",
    projectName: "Robotic Welding Cell Integration",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Vikram Singh",
    overallScore: 82,
    recommendation: "Approve with Minor Revisions",
    formData: { roboticsProjectTitle: "Robotic Welding Cell Integration", roboticsEngineer: "Vikram Singh" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Singh", action: "Record Created", description: "Robotics Integration record created." }],
  },
  {
    moduleType: "smart-factory-development",
    recordCode: "SF-2024-00015",
    formCode: "SFPF-2024-25",
    projectName: "EVSE Smart Factory Transformation",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Vikram Singh",
    overallScore: 80,
    recommendation: "Approve with Minor Revisions",
    formData: { smartFactoryProjectTitle: "EVSE Smart Factory Transformation", projectManager: "Vikram Singh" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Vikram Singh", action: "Record Created", description: "Smart Factory Development record created." }],
  },
  {
    moduleType: "routing-development",
    recordCode: "RTG-2024-000123",
    formCode: "RTD-2024-25",
    projectName: "Autonomous W-EVSE Manufacturing Routing",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 84,
    recommendation: "Approve with Minor Revisions",
    formData: { routingName: "Autonomous W-EVSE Manufacturing Routing", processOwner: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Routing Development record created." }],
  },
  {
    moduleType: "tooling-development",
    recordCode: "TOOL-2024-0078",
    formCode: "TDF-2024-25",
    projectName: "EV Charger Assembly Fixture",
    version: "1.0",
    workflowStatus: "In Progress",
    stage: 2,
    priority: "High",
    ownerName: "Rahul Sharma",
    overallScore: 80,
    recommendation: "Approve with Minor Revisions",
    formData: { projectName: "EV Charger Assembly Fixture", createdBy: "Rahul Sharma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rahul Sharma", action: "Record Created", description: "Tooling Development record created." }],
  },
  {
    moduleType: "commercialization",
    recordCode: "CMP-2024-0021",
    formCode: "CMP-2024-15",
    projectName: "Autonomous Docking System Commercialization Plan",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rohit Verma",
    overallScore: 83,
    recommendation: "Approve with Minor Revisions",
    formData: { commercializationProject: "Autonomous Docking System Commercialization Plan", commercializationManager: "Rohit Verma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rohit Verma", action: "Record Created", description: "Commercialization record created." }],
  },
  {
    moduleType: "trl-assessment",
    recordCode: "TRL-2024-0087",
    formCode: "TRL-2024-25",
    projectName: "Autonomous Docking System Readiness Assessment",
    version: "1.0",
    workflowStatus: "In Review",
    stage: 3,
    priority: "High",
    ownerName: "Rohit Verma",
    overallScore: 82,
    recommendation: "Approve with Minor Revisions",
    formData: { assessmentTitle: "Autonomous Docking System Readiness Assessment", assessmentLead: "Rohit Verma" },
    sectionScores: {},
    aiAssessment: {},
    reviewers: [],
    attachments: [],
    activities: [{ user: "Rohit Verma", action: "Record Created", description: "TRL Assessment record created." }],
  },
];

async function seedDevelopmentData() {
  console.log("Seeding development data...");

  for (const mod of SEED_MODULES) {
    const existing = await prisma.developmentRecord.findFirst({
      where: { moduleType: mod.moduleType, recordCode: mod.recordCode },
    });

    if (existing) {
      console.log(`  ✓ ${mod.moduleType} (${mod.recordCode}) already exists, skipping`);
      continue;
    }

    const record = await prisma.developmentRecord.create({
      data: {
        moduleType: mod.moduleType,
        recordCode: mod.recordCode,
        formCode: mod.formCode,
        projectName: mod.projectName,
        version: mod.version,
        workflowStatus: mod.workflowStatus,
        stage: mod.stage,
        priority: mod.priority,
        ownerName: mod.ownerName,
        ownerEmail: mod.ownerEmail ?? null,
        businessUnit: mod.businessUnit ?? null,
        department: mod.department ?? null,
        formData: mod.formData,
        sectionScores: mod.sectionScores,
        aiAssessment: mod.aiAssessment,
        overallScore: mod.overallScore,
        recommendation: mod.recommendation,
        approvalDecision: mod.approvalDecision ?? null,
      },
    });

    for (let i = 0; i < mod.reviewers.length; i++) {
      const r = mod.reviewers[i];
      await prisma.developmentApproval.create({
        data: {
          recordId: record.id,
          role: r.role,
          person: r.person,
          decision: r.decision,
          status: r.status,
          comments: r.comments,
          sortOrder: i,
        },
      });
    }

    for (const att of mod.attachments) {
      await prisma.developmentAttachment.create({
        data: {
          recordId: record.id,
          fileName: att.fileName,
          fileType: att.fileType,
          documentType: att.documentType,
          uploadedBy: att.uploadedBy,
          fileSize: att.fileSize,
          status: "Active",
        },
      });
    }

    for (const act of mod.activities) {
      await prisma.developmentActivityLog.create({
        data: {
          recordId: record.id,
          user: act.user,
          action: act.action,
          description: act.description,
        },
      });
    }

    console.log(`  ✓ ${mod.moduleType} (${mod.recordCode}) seeded with ${mod.reviewers.length} reviewers, ${mod.attachments.length} attachments, ${mod.activities.length} activities`);
  }

  console.log(`\nDone! Seeded ${SEED_MODULES.length} development records.`);
}

seedDevelopmentData()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
