/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  Activity,
  Award,
  CheckCircle2,
  Cpu,
  Layers,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  Zap,
} from "lucide-react";
import type { WidgetDefinition } from "../../types";
import { makeStatCardWidget } from "../shared/StatCardWidget";
import { RI_PANEL_WIDGETS } from "./panels";

export const riKpis: WidgetDefinition[] = [
  makeStatCardWidget({
    id: "kpi.ri.active-submodules",
    title: "Active R&I Submodules",
    description: "Total connected research, engineering, quality, and digital innovation modules.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: Layers,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-500",
    options: () => ({ queryKey: ["ri", "active-submodules"], queryFn: async () => ({ value: 27, statusText: "100% operational pipeline" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 27), delta: { label: "100% operational pipeline", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.composite-readiness",
    title: "Composite Readiness",
    description: "Aggregate engineering and compliance readiness score across all active programs.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: CheckCircle2,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-500",
    options: () => ({ queryKey: ["ri", "composite-readiness"], queryFn: async () => ({ value: "91.4%", statusText: "Lead: Smart EV Charger AC 7kW" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "91.4%"), delta: { label: "Lead: Smart EV Charger AC 7kW", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.active-workflows",
    title: "Active Workflows",
    description: "Active engineering baselines and qualification workflows progressing through gates.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: Activity,
    iconBg: "bg-purple-500/10",
    iconColor: "text-purple-500",
    options: () => ({ queryKey: ["ri", "active-workflows"], queryFn: async () => ({ value: 249, statusText: "Across 27 integrated streams" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 249), delta: { label: "Across 27 integrated streams", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.gate-adherence",
    title: "Gate Adherence Velocity",
    description: "Stage-gate milestone compliance and release schedule adherence.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: TrendingUp,
    iconBg: "bg-amber-500/10",
    iconColor: "text-amber-500",
    options: () => ({ queryKey: ["ri", "gate-adherence"], queryFn: async () => ({ value: "94.2%", statusText: "Launch: Q3/Q4 2024" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "94.2%"), delta: { label: "Launch: Q3/Q4 2024", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.ip-patents",
    title: "Patents & IP Filings",
    description: "Proprietary charging patents, utility designs, and trade secrets filed.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: Award,
    iconBg: "bg-teal-500/10",
    iconColor: "text-teal-500",
    options: () => ({ queryKey: ["ri", "ip-patents"], queryFn: async () => ({ value: 18, statusText: "4 granted, 14 published" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 18), delta: { label: "4 granted, 14 published", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.cae-simulations",
    title: "CAE & FEA Simulations",
    description: "Multi-physics structural, thermal, and CFD simulations executed with convergence.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: Activity,
    iconBg: "bg-indigo-500/10",
    iconColor: "text-indigo-500",
    options: () => ({ queryKey: ["ri", "cae-simulations"], queryFn: async () => ({ value: 342, statusText: "99.4% convergence" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 342), delta: { label: "99.4% convergence", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.trl-velocity",
    title: "TRL Advancement Rate",
    description: "Technology Readiness Level transition velocity from concept to qualification.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: Zap,
    iconBg: "bg-rose-500/10",
    iconColor: "text-rose-500",
    options: () => ({ queryKey: ["ri", "trl-velocity"], queryFn: async () => ({ value: "TRL 7.8", statusText: "+1.4 levels YTD" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "TRL 7.8"), delta: { label: "+1.4 levels YTD", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.zero-defect-rate",
    title: "Zero-Defect Design Rate",
    description: "First-pass design rule check and DFM/DFA engineering clearance rate.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: ShieldCheck,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-500",
    options: () => ({ queryKey: ["ri", "zero-defect-rate"], queryFn: async () => ({ value: "99.1%", statusText: "DFM validated" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "99.1%"), delta: { label: "DFM validated", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.ri.digital-twin-sync",
    title: "Digital Twin Sync Rate",
    description: "Real-time telemetry parity between CAD models, simulations, and field units.",
    category: "kpi",
    tags: ["kpi", "ri"],
    icon: Sparkles,
    iconBg: "bg-cyan-500/10",
    iconColor: "text-cyan-500",
    options: () => ({ queryKey: ["ri", "digital-twin-sync"], queryFn: async () => ({ value: "99.8%", statusText: "18 active twins" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "99.8%"), delta: { label: "18 active twins", direction: "up", tone: "positive" } }),
  }),
];

export const RI_KPI_WIDGETS: WidgetDefinition[] = [
  ...riKpis,
  ...RI_PANEL_WIDGETS,
];
