import {
  Activity,
  Cloud,
  Code,
  Cpu,
  Layers,
  Package,
  Palette,
  Repeat,
  Rocket,
  ShieldCheck,
  Smartphone,
  Target,
} from "lucide-react";
import type { WidgetDefinition } from "../../types";
import { makeStatCardWidget } from "../shared/StatCardWidget";
import { PD_PANEL_WIDGETS } from "./panels";

export const pdKpis: WidgetDefinition[] = [
  makeStatCardWidget({
    id: "kpi.pd.active-projects",
    title: "Active Projects",
    description: "Total active product engineering projects across design and build stages.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Package,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-500",
    options: () => ({ queryKey: ["pd", "active-projects"], queryFn: async () => ({ value: 18, statusText: "+3 this month" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 18), delta: { label: "+3 this month", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.in-development",
    title: "In Development",
    description: "Products currently undergoing detailed mechanical, electrical & software engineering.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Layers,
    iconBg: "bg-purple-500/10",
    iconColor: "text-purple-500",
    options: () => ({ queryKey: ["pd", "in-development"], queryFn: async () => ({ value: 12, statusText: "On schedule" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 12), delta: { label: "On schedule", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.ready-release",
    title: "Ready for Release",
    description: "Products passing validation and awaiting release gate approval.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Rocket,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-500",
    options: () => ({ queryKey: ["pd", "ready-release"], queryFn: async () => ({ value: 4, statusText: "1 pending review" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 4), delta: { label: "1 pending review", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.active-lifecycle",
    title: "In Active Lifecycle",
    description: "Products in active commercial lifecycle with active digital thread tracking.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Repeat,
    iconBg: "bg-amber-500/10",
    iconColor: "text-amber-500",
    options: () => ({ queryKey: ["pd", "active-lifecycle"], queryFn: async () => ({ value: 34, statusText: "ECR/ECO active" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 34), delta: { label: "ECR/ECO active", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.overall-health",
    title: "Overall Product Health",
    description: "Aggregate engineering quality, schedule compliance, and requirement satisfaction score.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Activity,
    iconBg: "bg-teal-500/10",
    iconColor: "text-teal-500",
    options: () => ({ queryKey: ["pd", "overall-health"], queryFn: async () => ({ value: "94%", statusText: "Optimal quality" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "94%"), delta: { label: "Optimal quality", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.strategy-baselines",
    title: "Strategy Baselines",
    description: "Approved product strategy portfolios and market positioning baselines.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Target,
    iconBg: "bg-indigo-500/10",
    iconColor: "text-indigo-500",
    options: () => ({ queryKey: ["pd", "strategy-baselines"], queryFn: async () => ({ value: 24, statusText: "100% aligned" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 24), delta: { label: "100% aligned", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.embedded-modules",
    title: "Firmware & Embedded Nodes",
    description: "Active embedded microcontroller and firmware modules running in field testing.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Cpu,
    iconBg: "bg-rose-500/10",
    iconColor: "text-rose-500",
    options: () => ({ queryKey: ["pd", "embedded-nodes"], queryFn: async () => ({ value: 12, statusText: "HIL verified" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 12), delta: { label: "HIL verified", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.cloud-apis",
    title: "Cloud Services & APIs",
    description: "Telemetry ingestion endpoints, cloud APIs, and microservices in staging.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: Cloud,
    iconBg: "bg-cyan-500/10",
    iconColor: "text-cyan-500",
    options: () => ({ queryKey: ["pd", "cloud-apis"], queryFn: async () => ({ value: 8, statusText: "99.9% uptime" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 8), delta: { label: "99.9% uptime", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.test-pass-rate",
    title: "Verification Test Pass Rate",
    description: "Automated regression and environmental validation test yield.",
    category: "kpi",
    tags: ["kpi", "pd"],
    icon: ShieldCheck,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-500",
    options: () => ({ queryKey: ["pd", "test-pass-rate"], queryFn: async () => ({ value: "98.6%", statusText: "Zero blockers" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "98.6%"), delta: { label: "Zero blockers", direction: "up", tone: "positive" } }),
  }),
];

export const pdWidgets: WidgetDefinition[] = [
  ...pdKpis,
  ...PD_PANEL_WIDGETS,
];
