import {
  DollarSign,
  Briefcase,
  PieChart as PieChartIcon,
  Banknote,
  BarChart3,
  LineChart,
  Waves,
  ReceiptText,
  Users,
  Sparkles,
} from "lucide-react";
import { formatCurrency } from "@/lib/format";
import type { WidgetDefinition } from "../../types";
import { dashboardDataOptions } from "../../data/queries";
import { makeStatCardWidget } from "../shared/StatCardWidget";
import {
  AgingPayableWidget,
  AgingReceivableWidget,
  CashFlowWidget,
  ExpenseDonutWidget,
  QuickInsightsWidget,
  RecentTransactionsWidget,
  RevenueTrendWidget,
} from "./panels";

/* ===========================================================================
   Dashboard widget definitions
   The five KPI entries reproduce the Dashboard's original StatCards exactly,
   including the hardcoded vs.-prior-year delta strings that were literals in
   the page (they are not data fields — preserved verbatim to avoid changing
   what the page reports).
   =========================================================================== */

export const DASHBOARD_WIDGETS: WidgetDefinition[] = [
  makeStatCardWidget({
    id: "kpi.total-revenue",
    title: "Total Revenue",
    description: "Year-to-date revenue across all stations and channels.",
    category: "kpi",
    tags: ["finance", "analytics"],
    icon: DollarSign,
    keywords: ["revenue", "sales", "income", "turnover"],
    iconBg: "bg-primary/10",
    iconColor: "text-primary",
    options: dashboardDataOptions,
    map: (d) => ({
      value: formatCurrency(d.totalRevenue, true),
      delta: { label: "12.6% vs. PY", direction: "up", tone: "positive" },
    }),
  }),
  makeStatCardWidget({
    id: "kpi.net-profit",
    title: "Net Profit",
    description: "Revenue less all expenses, year to date.",
    category: "kpi",
    tags: ["finance", "analytics"],
    icon: Briefcase,
    keywords: ["profit", "margin", "bottom line", "earnings"],
    iconBg: "bg-[#22C55E]/10",
    iconColor: "text-[#22C55E]",
    options: dashboardDataOptions,
    map: (d) => ({
      value: formatCurrency(d.netProfit, true),
      delta: { label: "8.9% vs. PY", direction: "up", tone: "positive" },
    }),
  }),
  makeStatCardWidget({
    id: "kpi.total-expenses",
    title: "Total Expenses",
    description: "Total operating and non-operating expenses, year to date.",
    category: "kpi",
    tags: ["finance", "analytics"],
    icon: PieChartIcon,
    keywords: ["expenses", "costs", "spend", "opex"],
    iconBg: "bg-[#3B82F6]/10",
    iconColor: "text-[#3B82F6]",
    options: dashboardDataOptions,
    map: (d) => ({
      value: formatCurrency(d.totalExpenses, true),
      delta: { label: "9.3% vs. PY", direction: "up", tone: "positive" },
    }),
  }),
  makeStatCardWidget({
    id: "kpi.cash-balance",
    title: "Cash Balance",
    description: "Consolidated cash position across all bank accounts.",
    category: "kpi",
    tags: ["banking", "finance"],
    icon: Banknote,
    keywords: ["cash", "bank", "liquidity", "balance"],
    iconBg: "bg-[#F59E0B]/10",
    iconColor: "text-[#F59E0B]",
    sourceRoute: "/management/finance/cash-bank",
    options: dashboardDataOptions,
    map: (d) => ({
      value: formatCurrency(d.cashPosition.cashBalance, true),
      delta: { label: "15.2% vs. PY", direction: "up", tone: "positive" },
    }),
  }),
  makeStatCardWidget({
    id: "kpi.current-ratio",
    title: "Current Ratio",
    description: "Current assets divided by current liabilities.",
    category: "kpi",
    tags: ["analytics", "finance"],
    icon: BarChart3,
    keywords: ["ratio", "liquidity", "solvency", "working capital"],
    iconBg: "bg-primary/10",
    iconColor: "text-primary",
    options: dashboardDataOptions,
    map: (d) => ({
      value: d.currentRatio.currentRatio.toFixed(2),
      neutralText: `vs. PY ${d.currentRatio.currentRatioPY.toFixed(2)}`,
    }),
  }),

  {
    id: "chart.revenue-expense-trend",
    title: "Revenue vs. Expenses Trend",
    description: "Monthly revenue and expense bars with a net profit trend line.",
    category: "chart",
    tags: ["finance", "analytics"],
    icon: LineChart,
    keywords: ["trend", "revenue", "expenses", "profit", "monthly", "chart"],
    defaultSize: "lg",
    allowedSizes: ["md", "lg", "xl", "full"],
    roles: "all",
    dataKey: dashboardDataOptions().queryKey,
    component: RevenueTrendWidget,
  },
  {
    id: "list.cash-flow-summary",
    title: "Cash Flow Summary",
    description: "Operating, investing and financing cash flows with the net position.",
    category: "list",
    tags: ["banking", "finance"],
    icon: Waves,
    keywords: ["cash flow", "operating", "investing", "financing"],
    defaultSize: "md",
    allowedSizes: ["md", "lg", "xl", "full"],
    roles: "all",
    dataKey: dashboardDataOptions().queryKey,
    component: CashFlowWidget,
  },
  {
    id: "chart.expense-donut",
    title: "Expense Distribution",
    description: "Share of total expenses by category.",
    category: "chart",
    tags: ["analytics", "finance"],
    icon: PieChartIcon,
    keywords: ["expenses", "distribution", "donut", "breakdown", "categories"],
    defaultSize: "md",
    allowedSizes: ["md", "lg", "xl", "full"],
    roles: "all",
    dataKey: dashboardDataOptions().queryKey,
    component: ExpenseDonutWidget,
  },
  {
    id: "chart.aging-receivable",
    title: "Aging of Accounts Receivable",
    description: "Receivables split across aging buckets with totals.",
    category: "receivables",
    tags: ["chart", "finance"],
    icon: Users,
    keywords: ["aging", "receivable", "ar", "overdue", "customers"],
    defaultSize: "md",
    allowedSizes: ["md", "lg", "xl", "full"],
    roles: "all",
    sourceRoute: "/management/finance/receivables",
    dataKey: dashboardDataOptions().queryKey,
    component: AgingReceivableWidget,
  },
  {
    id: "chart.aging-payable",
    title: "Aging of Accounts Payable",
    description: "Payables split across aging buckets with totals.",
    category: "payables",
    tags: ["chart", "finance"],
    icon: ReceiptText,
    keywords: ["aging", "payable", "ap", "overdue", "vendors"],
    defaultSize: "md",
    allowedSizes: ["md", "lg", "xl", "full"],
    roles: "all",
    sourceRoute: "/management/finance/payables",
    dataKey: dashboardDataOptions().queryKey,
    component: AgingPayableWidget,
  },
  {
    id: "table.recent-transactions",
    title: "Recent Transactions",
    description: "The latest posted transactions across the ledger.",
    category: "table",
    tags: ["finance", "ledger"],
    icon: ReceiptText,
    keywords: ["transactions", "recent", "activity", "ledger"],
    defaultSize: "md",
    allowedSizes: ["md", "lg", "xl", "full"],
    roles: "all",
    sourceRoute: "/transactions",
    dataKey: dashboardDataOptions().queryKey,
    component: RecentTransactionsWidget,
  },
  {
    id: "insight.quick-financial",
    title: "Quick Financial Insights",
    description: "Margins, expense ratio, DSO, DPO and the cash conversion cycle.",
    category: "insight",
    tags: ["analytics", "finance"],
    icon: Sparkles,
    keywords: ["insights", "margin", "dso", "dpo", "ratio", "cash conversion"],
    defaultSize: "full",
    allowedSizes: ["lg", "xl", "full"],
    roles: "all",
    dataKey: dashboardDataOptions().queryKey,
    component: QuickInsightsWidget,
  },
];
