export const RESEARCH_INNOVATION_NAV_ORDER = [
  { label: "Overview", path: "/development/research-innovation/overview" },
  { label: "Certification", path: "/development/research-innovation/certification-readiness/new" },
  { label: "Documentation", path: "/development/research-innovation/product-documentation/new" },
  { label: "Release", path: "/development/research-innovation/product-release-management/new" },
  { label: "Testing", path: "/development/research-innovation/testing-validation/new" },
  { label: "Simulation", path: "/development/research-innovation/simulation-analysis/new" },
  { label: "Cybersecurity", path: "/development/research-innovation/cybersecurity-engineering/new" },
  { label: "Cloud Platform", path: "/development/research-innovation/cloud-platform-development/new" },
  { label: "AI Model", path: "/development/research-innovation/ai-model-development/new" },
  { label: "UI/UX", path: "/development/research-innovation/ui-ux-development/new" },
  { label: "Production Eng", path: "/development/research-innovation/production-engineering/new" },
  { label: "Assembly Line", path: "/development/research-innovation/assembly-line-development/new" },
  { label: "Fixture Dev", path: "/development/research-innovation/fixture-development/new" },
  { label: "Tooling Dev", path: "/development/research-innovation/tooling-development/new" },
  { label: "Jig Dev", path: "/development/research-innovation/jig-development/new" },
  { label: "Factory Layout", path: "/development/research-innovation/factory-layout-design/new" },
  { label: "Capacity Plan", path: "/development/research-innovation/capacity-planning/new" },
  { label: "Work Instruction", path: "/development/research-innovation/work-instruction-development/new" },
  { label: "SOP Dev", path: "/development/research-innovation/sop-development/new" },
  { label: "BOM Eng", path: "/development/research-innovation/bom-engineering/new" },
  { label: "Routing Dev", path: "/development/research-innovation/routing-development/new" },
  { label: "APQP Quality", path: "/development/research-innovation/quality-planning-apqp/new" },
  { label: "PFMEA Dev", path: "/development/research-innovation/pfmea-development/new" },
  { label: "Control Plan", path: "/development/research-innovation/control-plan/new" },
  { label: "Process Validation", path: "/development/research-innovation/process-validation/new" },
  { label: "Smart Factory", path: "/development/research-innovation/smart-factory-development/new" },
  { label: "Excellence", path: "/development/research-innovation/manufacturing-excellence/new" },
  { label: "API", path: "/development/research-innovation/api-development/new" },
];
